import { useState } from 'react'
const fmt = n => new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 }).format(n)
export default function MathLab({ kind }) {
  const [a, setA] = useState(3)
  const [b, setB] = useState(4)
  const [x, setX] = useState(0)
  const [runs, setRuns] = useState([])
  const [step, setStep] = useState(0)
  const slider = (label, value, set, min, max) => <label className="lab-slider">{label} : <strong>{value}</strong><input type="range" min={min} max={max} value={value} onChange={e => set(Number(e.target.value))} /></label>
  return <section id="laboratoire" className="lesson-block math-lab"><span className="eyebrow">Je manipule</span>
    {kind === 'pythagoras' && <><h2>Un triangle qui change, une égalité qui reste</h2><p>Modifie les deux côtés de l’angle droit. Prévois la longueur de l’hypoténuse, puis vérifie.</p><div className="lab-layout"><div>{slider('AB (cm)', a, setA, 1, 10)}{slider('AC (cm)', b, setB, 1, 10)}<p aria-live="polite">BC² = {a}² + {b}² = {a*a+b*b}<br /><strong>BC = √{a*a+b*b} ≈ {fmt(Math.hypot(a,b))} cm</strong></p></div><svg viewBox="0 0 340 300" role="img" aria-label={`ABC rectangle en A, AB ${a} cm, AC ${b} cm, BC environ ${fmt(Math.hypot(a,b))} cm`}><path d={`M40 250 L${40+a*21} 250 L40 ${250-b*21} Z`} fill="#eaf0ff" stroke="#355da9" strokeWidth="3"/><path d="M40 236 H54 V250" fill="none" stroke="#355da9"/><text x="21" y="273">A</text><text x={40+a*21} y="273">B</text><text x="20" y={245-b*21}>C</text></svg></div></>}
    {kind === 'equation' && <><h2>Équilibrer les deux membres</h2><p>Pour quelle valeur de x l’égalité 3x + 2 = 14 est-elle vraie ?</p>{slider('Valeur de x', x, setX, -5, 10)}<div className="balance-values"><div>3x + 2<strong>{3*x+2}</strong></div><span>{3*x+2===14 ? '=' : 3*x+2<14 ? '<' : '>'}</span><div>Membre droit<strong>14</strong></div></div><p role="status">{x===4 ? 'Égalité vérifiée ! 3 × 4 + 2 = 14. La solution est x = 4.' : 'Les deux membres sont différents. Ajuste x pour trouver l’équilibre.'}</p></>}
    {kind === 'graph' && <><h2>Lire une distance sur un graphique</h2><p>Un marcheur avance à 4 km/h. Déplace le temps : la distance vaut d = 4 × t.</p>{slider('Temps (h)', x, setX, 0, 5)}<svg viewBox="0 0 400 290" role="img" aria-label={`Graphique distance en fonction du temps : ${x} heures, ${4*x} kilomètres`}><path d="M45 15 V245 H360" stroke="#66728a" fill="none"/>{[0,1,2,3,4,5].map(i=><g key={i}><text x={40+i*58} y="268">{i}</text><text x="12" y={250-i*42}>{i*4}</text><path d={`M45 ${245-i*42} H335`} stroke="#dde4e0"/></g>)}<path d="M45 245 L335 35" stroke="#355da9" strokeWidth="3"/><path d={`M${45+x*58} 245 V${245-x*42} H45`} fill="none" stroke="#996829" strokeDasharray="5 5"/><circle cx={45+x*58} cy={245-x*42} r="6" fill="#355da9"/><text x="48" y="15">Distance (km)</text><text x="275" y="288">Temps (h)</text></svg><p aria-live="polite"><strong>{x} h → {x*4} km</strong>. La droite passe par l’origine : les grandeurs sont proportionnelles.</p></>}
    {kind === 'probability' && <><h2>Probabilité et fréquence observée</h2><p>On lance un dé équilibré et on compte les résultats pairs. La probabilité théorique est 3/6 = 50 %. Prévois ce qui va se passer sur plusieurs essais.</p><div className="lab-actions"><button className="button primary" onClick={() => setRuns(old => [...old, ...Array.from({length: 20}, () => 1+Math.floor(Math.random()*6))])}>Lancer 20 fois</button><button className="button secondary" onClick={() => setRuns([])}>Effacer les essais</button></div><p role="status">{runs.length ? `${runs.length} lancers : ${runs.filter(n=>n%2===0).length} résultats pairs, soit ${fmt(runs.filter(n=>n%2===0).length/runs.length*100)} %.` : 'Aucun lancer effectué.'}</p>{runs.length > 0 && <p>Derniers résultats : {runs.slice(-20).join(' · ')}</p>}<p>La fréquence peut s’éloigner de 50 %. Sur beaucoup de lancers, elle tend à se stabiliser autour de 50 %, sans garantie de s’en rapprocher à chaque série.</p></>}
    {kind === 'algorithm' && <><h2>Exécuter une boucle pas à pas</h2><pre className="algorithm-code">{'Au clic sur le drapeau\nMettre x à 1\nRépéter 4 fois : ajouter 3 à x\nSi x > 10 : dire « gagné »\nSinon : dire « encore »'}</pre><p>Prévois la valeur avant d’exécuter chaque tour.</p><div className="lab-actions"><button className="button primary" disabled={step===4} onClick={() => setStep(step+1)}>Exécuter un tour</button><button className="button secondary" onClick={() => setStep(0)}>Repartir de 1</button></div><p role="status">Tour {step}/4 · x = <strong>{1+3*step}</strong>{step===4 && ' · Condition vraie : « gagné »'}</p><ol start="0">{Array.from({length:step+1},(_,i)=><li key={i}>{i===0 ? 'Initialisation' : `Après le tour ${i}`} : x = {1+3*i}</li>)}</ol></>}
  </section>
}

