import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { sixthLessons } from '../content/lessons/sixieme'
import { memoryCards } from '../content/memoryCards'
import { readProgress } from '../content/progress'
const icons={'Nombres et calculs':'123','Fractions':'½','Grandeurs et mesures':'cm','Espace et géométrie':'△','Données et probabilités':'▥','Proportionnalité':'×2','Pensée informatique':'↪'}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
export default function SixthLevel({level}){
 const [search,setSearch]=useState('')
 const [filter,setFilter]=useState('all')
 const progress=readProgress()
 const completed=sixthLessons.filter(l=>Number.isFinite(progress[l.slug]?.score))
 const needsReview=l=>Number.isFinite(progress[l.slug]?.lastScore??progress[l.slug]?.score)&&(progress[l.slug].lastScore??progress[l.slug].score)<l.quiz.length
 const next=sixthLessons.find(needsReview)||sixthLessons.find(l=>!Number.isFinite(progress[l.slug]?.score))||sixthLessons[0]
 const chapters=level.chapters.map(c=>({...c,lessons:c.lessons.filter(l=>normalize(l.title+' '+c.title).includes(normalize(search))&&(filter==='all'||needsReview(l)))})).filter(c=>c.lessons.length)
 useEffect(()=>{document.title='Les maths en 6e · MathSimple';window.scrollTo(0,0)},[])
 return <section className="page-section sixth-level"><header className="sixth-heading"><div><span className="eyebrow">Mon parcours · 6e · 2026–2027</span><h1>Un petit pas.<br/><em>Une idée comprise.</em></h1><p>Tu peux chercher, te tromper et recommencer.<br/>Choisis une leçon : on avance ensemble.</p></div><div className="sixth-progress"><strong>{completed.length}<small>/{sixthLessons.length}</small></strong><span>quiz terminés</span><progress max={sixthLessons.length} value={completed.length} aria-label="Quiz de sixième terminés"/><Link to="/progression">Mes résultats</Link></div></header>
 <div className="sixth-start"><article className="sixth-mission"><span className="eyebrow">Ma prochaine petite séance</span><h2>{next.title}</h2><p>Un exemple, deux essais, trois questions.<br/>Prévois 10 à 15 minutes et un brouillon.</p><Link className="button primary" to={`/niveau/6e/lecon/${next.slug}`}>C’est parti →</Link></article><article className="sixth-memory"><span className="eyebrow">Mon rituel de 5 minutes</span><h2>Je muscle ma mémoire</h2><p>Tables, fractions, règles de géométrie…<br/>{memoryCards['6e'].length} cartes à retourner, sans chronomètre.</p><Link className="button secondary" to="/cartes-memoire/6e">Ouvrir mes cartes →</Link></article></div>
 <div className="sixth-road"><span><b>1</b> Je comprends</span><span><b>2</b> J’essaie</span><span><b>3</b> Je retiens</span></div>
 <div className="sixth-program-heading"><div><span className="eyebrow">À explorer</span><h2>Mes {level.chapters.length} univers de maths</h2></div><p>{sixthLessons.length} leçons · {sixthLessons.length*2} exercices · {sixthLessons.length*3} questions de quiz</p></div>
 <div className="course-toolbar"><label>Je cherche une notion<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex. : fraction, angle, durée…"/></label><label>Je veux voir<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toutes les leçons</option><option value="review">Mes notions à retravailler</option></select></label></div><p role="status">{chapters.reduce((n,c)=>n+c.lessons.length,0)} leçon(s) affichée(s){filter==='review'?' · Dernier quiz : moins de 3 bonnes réponses.':''}</p>
 <div className="sixth-chapters">{chapters.map(c=><article className={`sixth-chapter theme-${level.chapters.findIndex(ch=>ch.title===c.title)%4}`} key={c.title}><div className="sixth-chapter-title"><span aria-hidden="true">{icons[c.title]}</span><div><small>{c.lessons.length} leçon(s)</small><h2>{c.title}</h2></div></div><ul>{c.lessons.map(l=><li key={l.slug}><Link to={`/niveau/6e/lecon/${l.slug}`}><span>{l.title}</span><small>{Number.isFinite(progress[l.slug]?.score)?`Meilleur quiz : ${progress[l.slug].score}/${l.quiz.length}`:l.lab?'Cours · Manipulation · Quiz':'Cours · Exercices · Quiz'}<b aria-hidden="true"> →</b></small></Link></li>)}</ul></article>)}</div>
 {!chapters.length&&<div className="empty-state"><h2>{search?'Aucune leçon ne correspond':'Aucune notion signalée à retravailler'}</h2><p>{search?'Essaie un mot plus court.':'Tes quiz avec moins de 3 bonnes réponses apparaîtront ici.'}</p><button className="button secondary" onClick={()=>{setSearch('');setFilter('all')}}>Retrouver toutes les leçons</button></div>}
 <details className="curriculum-note"><summary>Pour les parents et les enseignants</summary><p>Leçons originales organisées selon le programme de sixième publié en avril 2025, applicable en 2026–2027. Elles associent des repères, un exemple résolu, des exercices et un court quiz. Les constructions se pratiquent aussi sur papier avec règle, équerre, compas et rapporteur.</p><p><a href="https://www.education.gouv.fr/sites/default/files/programme-de-math-matiques-pour-le-cycle-3-439827.pdf">Programme officiel de cycle 3 (PDF)</a> · <a href="https://eduscol.education.gouv.fr/5712/ressources-d-accompagnement-du-programme-de-mathematiques-au-cycle-3">Ressources Éduscol</a></p></details><Link className="back-link" to="/">← Tous les niveaux</Link>
 </section>
}
