import { useState } from 'react'
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:3}).format(n)
export default function SixthLab({kind}){
 const [n,setN]=useState(3),[d,setD]=useState(4),[a,setA]=useState(4),[b,setB]=useState(3),[angle,setAngle]=useState(60),[show,setShow]=useState(false),[step,setStep]=useState(0)
 const range=(label,value,set,min,max)=><label className="lab-slider">{label} : <strong>{value}</strong><input type="range" min={min} max={max} value={value} onChange={e=>set(Number(e.target.value))}/></label>
 return <section className="lesson-block sixth-lab" id="laboratoire"><span className="eyebrow">J’apprends en manipulant</span>
 {kind==='fraction'&&<><h2>Des parts, puis des nombres</h2><p>Chaque bande représente une unité. Prévois ce qui se passe quand tu dépasses une bande entière.</p><label className="lab-select">Parts égales dans une unité<select value={d} onChange={e=>{const next=Number(e.target.value);setD(next);setN(Math.min(n,next*2))}}>{[2,3,4,5,6,8].map(v=><option key={v} value={v}>{v} parts</option>)}</select></label>{range('Nombre de parts prises',n,setN,0,d*2)}<div className="fraction-bands" role="img" aria-label={`${n} parts sur ${d} par unité, soit ${n}/${d}`}>{[0,1].map(row=><div key={row}><small>Unité {row+1}</small><div className="fraction-strip" style={{gridTemplateColumns:`repeat(${d},1fr)`}}>{Array.from({length:d},(_,i)=><span key={i} className={row*d+i<n?'filled':''}>{row*d+i<n?'✓':''}</span>)}</div></div>)}</div><p className="lab-conclusion" aria-live="polite"><strong>{n}/{d}</strong> = {Math.floor(n/d)} unité(s) et {n%d}/{d}. {n>d?'Une fraction peut dépasser 1.':n===d?'La bande est entière : la fraction vaut 1.':'Les parts ont toutes la même taille.'}</p></>}
 {kind==='place'&&<><h2>La place du chiffre fait sa valeur</h2><p>Modifie le nombre de millièmes. Observe les échanges entre les colonnes.</p>{range('Unités entières',a,setA,0,9)}{range('Millièmes ajoutés',n,setN,0,999)}<div className="place-table">{['Unités','Dixièmes','Centièmes','Millièmes'].map((label,i)=><div key={label}><span>{label}</span><strong>{[a,Math.floor(n/100),Math.floor(n/10)%10,n%10][i]}</strong></div>)}</div><p className="lab-conclusion" aria-live="polite"><strong>{fmt(a+n/1000)}</strong> = {a} + {Math.floor(n/100)}/10 + {Math.floor(n/10)%10}/100 + {n%10}/1 000.</p><p>Essaie 9 millièmes, puis 10, puis 100. Dix millièmes forment un centième.</p></>}
 {kind==='area'&&<><h2>Le contour ou la surface ?</h2><p>Chaque petit carré mesure 1 cm de côté. Compte-les avant de lire le résultat.</p><div className="lab-layout"><div>{range('Longueur (cm)',a,setA,1,8)}{range('Largeur (cm)',b,setB,1,6)}</div><svg viewBox="0 0 320 240" role="img" aria-label={`Rectangle de ${a} cm sur ${b} cm, partagé en ${a*b} carrés de 1 cm²`}>{Array.from({length:a*b},(_,i)=><rect key={i} x={35+(i%a)*30} y={30+Math.floor(i/a)*30} width="30" height="30" fill="#d6f4ee" stroke="#218576"/>)}<rect x="35" y="30" width={a*30} height={b*30} fill="none" stroke="#6950b7" strokeWidth="4"/><text x="35" y={50+b*30}>{a} cm × {b} cm</text></svg></div><div className="area-results" aria-live="polite"><p><span>Surface intérieure</span><strong>{a*b} cm²</strong>{a} × {b}</p><p><span>Longueur du contour</span><strong>{2*(a+b)} cm</strong>2 × ({a} + {b})</p></div><p>Compare 4 × 3 et 5 × 2 : même périmètre, mais aires différentes.</p></>}
 {kind==='angle'&&<><h2>Ouvre l’angle et observe</h2><p>Pars du côté horizontal à droite : c’est le zéro de notre graduation.</p>{range('Angle en degrés',angle,setAngle,10,170)}<svg viewBox="0 0 360 230" role="img" aria-label={`Angle de ${angle} degrés${show?`, partagé en deux angles de ${angle/2} degrés`:''}`}><path d="M30 190 A150 150 0 0 1 330 190" fill="none" stroke="#bcc8db"/>{Array.from({length:19},(_,i)=>{const r=i*10*Math.PI/180;return <line key={i} x1={180+140*Math.cos(r)} y1={190-140*Math.sin(r)} x2={180+150*Math.cos(r)} y2={190-150*Math.sin(r)} stroke="#65718b"/>})}<path d={`M320 190 H180 L${180+135*Math.cos(angle*Math.PI/180)} ${190-135*Math.sin(angle*Math.PI/180)}`} fill="none" stroke="#285bc1" strokeWidth="4"/>{show&&<line x1="180" y1="190" x2={180+135*Math.cos(angle*Math.PI/360)} y2={190-135*Math.sin(angle*Math.PI/360)} stroke="#ad501e" strokeWidth="3" strokeDasharray="6 4"/>}<text x="325" y="213">0°</text><text x="164" y="28">90°</text><text x="10" y="213">180°</text><text x="175" y="216">O</text></svg><p className="lab-conclusion" aria-live="polite">{angle}° : angle {angle<90?'aigu':angle===90?'droit':'obtus'}.{show&&` Chaque moitié mesure ${fmt(angle/2)}°.`}</p><button className="button secondary" aria-pressed={show} onClick={()=>setShow(!show)}>{show?'Masquer la bissectrice':'Voir la bissectrice'}</button></>}
 {kind==='symmetry'&&<><h2>De l’autre côté du miroir</h2><p>Prévois où se trouve A′, puis affiche son image.</p>{range('Distance de A à l’axe (carreaux)',a,setA,1,4)}<svg viewBox="0 0 360 220" role="img" aria-label={`A à ${a} carreaux à gauche de l’axe vertical${show?`, A′ à ${a} carreaux à droite`:''}`}>{Array.from({length:11},(_,i)=><line key={i} x1={30+i*30} x2={30+i*30} y1="30" y2="190" stroke="#d6dce5"/>)}{[40,70,100,130,160,190].map(y=><line key={y} x1="30" x2="330" y1={y} y2={y} stroke="#d6dce5"/>)}<line x1="180" x2="180" y1="20" y2="200" stroke="#6950b7" strokeWidth="3"/><text x="189" y="20">axe</text><circle cx={180-a*30} cy="100" r="6" fill="#285bc1"/><text x={173-a*30} y="87">A</text>{show&&<><path d={`M${180-a*30} 100 H${180+a*30}`} stroke="#ad501e" strokeDasharray="5 4"/><circle cx={180+a*30} cy="100" r="6" fill="#ad501e"/><text x={173+a*30} y="87">A′</text></>}</svg><button className="button secondary" aria-pressed={show} onClick={()=>setShow(!show)}>{show?'Cacher l’image':'Afficher l’image de A'}</button>{show&&<p role="status">A′ est à {a} carreaux à droite, à la même hauteur. AA′ mesure {a*2} carreaux.</p>}</>}
 {kind==='ratio'&&<><h2>Adapte la recette</h2><p>Pour quatre personnes, on prévoit 300 g de riz. La quantité par personne reste la même.</p>{range('Nombre de personnes',a,setA,1,8)}<table className="ratio-table"><caption>Quantité de riz</caption><thead><tr><th scope="col">Personnes</th><th scope="col">1</th><th scope="col">4</th><th scope="col">{a}</th></tr></thead><tbody><tr><th scope="row">Riz (g)</th><td>75</td><td>300</td><td>{a*75}</td></tr></tbody></table><p className="lab-conclusion" aria-live="polite">300 ÷ 4 = 75 g par personne.<br/><strong>{a} × 75 = {a*75} g</strong> pour {a} personne(s).</p><p>Essaie 2, puis 8 personnes. La quantité est divisée par deux, puis multipliée par deux par rapport à la recette de départ.</p></>}
 {kind==='steps'&&<><h2>Une boucle, un pas à la fois</h2><p>Départ : 0. Instruction : répéter 4 fois « avancer de 2 ».</p><div className="step-track" role="img" aria-label={`Position ${step*2} après ${step} répétition(s)`}>{Array.from({length:9},(_,i)=><span key={i} className={step*2===i?'current':''}>{i}</span>)}</div><div className="lab-actions"><button className="button primary" disabled={step===4} onClick={()=>setStep(step+1)}>Exécuter un tour</button><button className="button secondary" onClick={()=>setStep(0)}>Recommencer</button></div><p className="lab-conclusion" role="status">{step} tour(s) sur 4 · Position {step*2}.{step===4?' Boucle terminée : 4 × 2 = 8.':''}</p><p>Explique pourquoi le premier déplacement mène à 2 et non à 1.</p></>}
 </section>
}
