// Contenus originaux, organisés selon les attendus de 4e applicables en 2026-2027.
const q = (question, choices, correct, explanation) => ({ question, choices, correct, explanation })
const ex = (question, answer, hint, solution) => ({ question, answer, hint, solution })
const lesson = (slug, chapter, title, prerequisite, rules, example, exercises, quiz, lab) => ({
  slug, level: '4e', chapter, title, prerequisite, duration: '15 à 25 min',
  objectives: rules.map(r => r[0]), rules, example, exercises, quiz, lab,
})

export const fourthLessons = [
  lesson('produits-quotients-relatifs', 'Nombres relatifs et rationnels', 'Multiplier et diviser des relatifs', 'Additionner et soustraire des nombres relatifs.', [
    ['Déterminer le signe', 'Pour un produit ou un quotient de deux nombres non nuls : même signe → positif ; signes différents → négatif. Calcule ensuite avec les distances à zéro.'],
    ['Respecter les priorités', 'Parenthèses, puissances, puis multiplications et divisions, puis additions et soustractions. À priorité égale, avance de gauche à droite.'],
    ['Contrôler un calcul', 'Un nombre pair de facteurs négatifs donne un produit positif ; un nombre impair donne un produit négatif. Un facteur nul donne zéro. On ne divise jamais par zéro.'],
  ], ['Calculer −7 + (−3) × (−4)', 'Effectue d’abord le produit : (−3) × (−4) = 12.', 'Puis calcule −7 + 12 = 5.', 'Le résultat est 5. La règle des signes du produit ne s’applique pas à une addition.'], [
    ex('(−8) × (−6) = ?', 48, 'Commence par le signe, puis calcule 8 × 6.', 'Deux facteurs négatifs donnent un produit positif : 8 × 6 = 48.'),
    ex('La température baisse de 3 °C par heure pendant 4 h. Elle était de 5 °C. Quelle est la température finale en °C ?', -7, 'Traduis la baisse par −3.', '5 + 4 × (−3) = 5 − 12 = −7 °C.'),
  ], [q('(−35) ÷ 5 = ?', ['−7', '7', '−30'], 0, 'Les signes sont différents et 35 ÷ 5 = 7.'), q('6 − 2 × 5 = ?', ['20', '−4', '−20'], 1, 'La multiplication précède la soustraction : 6 − 10 = −4.'), q('Le produit de trois nombres négatifs non nuls est…', ['positif', 'nul', 'négatif'], 2, 'Trois est impair : le produit est négatif.')]),
  lesson('fractions-operations', 'Nombres relatifs et rationnels', 'Comparer et calculer avec les fractions', 'Connaître numérateur et dénominateur.', [
    ['Comparer des rationnels', 'Écris les fractions avec un même dénominateur positif, puis compare leurs numérateurs. Par exemple −2/3 = −8/12 < −7/12.'],
    ['Additionner et multiplier', 'Pour additionner, utilise un dénominateur commun et additionne les numérateurs. Pour multiplier, multiplie les numérateurs entre eux et les dénominateurs entre eux. Simplifie les facteurs communs.'],
    ['Diviser par une fraction', 'L’inverse de a/b est b/a si a et b sont non nuls. Diviser par une fraction non nulle, c’est multiplier par son inverse.'],
  ], ['Calculer 5/6 − (1/3 × 3/4)', 'La multiplication est prioritaire : 1/3 × 3/4 = 3/12 = 1/4.', 'Prends le dénominateur commun 12 : 5/6 = 10/12 et 1/4 = 3/12.', '10/12 − 3/12 = 7/12. On n’additionne jamais les dénominateurs.'], [
    ex('3/8 + 1/4 = ? (fraction ou décimal)', .625, 'Transforme 1/4 en huitièmes.', '3/8 + 2/8 = 5/8 = 0,625.'),
    ex('Une bouteille contient 3/4 L. Combien de verres de 1/8 L peut-on remplir ?', 6, 'Divise la quantité totale par la quantité par verre.', '(3/4) ÷ (1/8) = (3/4) × 8 = 6 verres.'),
  ], [q('−3/4 comparé à −2/3 donne…', ['−3/4 < −2/3', '−3/4 > −2/3', 'égalité'], 0, '−3/4 = −9/12 et −2/3 = −8/12.'), q('L’inverse de −5/2 est…', ['5/2', '−2/5', '2/5'], 1, 'Le produit (−5/2) × (−2/5) vaut 1.'), q('2/5 × 3/7 = ?', ['5/12', '6/12', '6/35'], 2, 'On multiplie les numérateurs et les dénominateurs.')]),
  lesson('nombres-premiers', 'Nombres relatifs et rationnels', 'Nombres premiers et fractions irréductibles', 'Utiliser les tables de multiplication.', [
    ['Reconnaître un nombre premier', 'Un entier supérieur à 1 est premier s’il a exactement deux diviseurs positifs : 1 et lui-même. 1 n’est pas premier ; 2 est le seul nombre premier pair.'],
    ['Décomposer un entier', 'Divise successivement par 2, 3, 5, 7… tant que possible. Pour tester un nombre inférieur à 100, il suffit de vérifier les diviseurs premiers 2, 3, 5 et 7, sans oublier que ces quatre nombres sont eux-mêmes premiers.'],
    ['Simplifier une fraction', 'Décompose le numérateur et le dénominateur en facteurs premiers puis supprime les facteurs communs. Une fraction est irréductible lorsqu’il ne reste aucun diviseur commun supérieur à 1.'],
  ], ['Simplifier 84/126', '84 = 2 × 2 × 3 × 7 et 126 = 2 × 3 × 3 × 7.', 'Divise le numérateur et le dénominateur par 2 × 3 × 7 = 42.', '84/126 = 2/3, fraction irréductible.'], [
    ex('Quel est le plus petit diviseur premier de 91 ?', 7, 'Teste 2, 3, 5, puis 7.', '91 = 7 × 13. Il n’est divisible ni par 2, ni par 3, ni par 5.'),
    ex('On partage 24 crayons et 36 gommes en un maximum de lots identiques sans reste. Combien de lots ?', 12, 'Cherche le plus grand diviseur commun.', '24 = 2³ × 3 et 36 = 2² × 3². Leur plus grand diviseur commun est 2² × 3 = 12 : 2 crayons et 3 gommes par lot.'),
  ], [q('Quel nombre est premier ?', ['51', '57', '59'], 2, '51 = 3 × 17, 57 = 3 × 19. 59 n’est divisible ni par 2, 3, 5, ni par 7.'), q('La décomposition de 90 est…', ['2 × 3² × 5', '9 × 10', '2 × 5²'], 0, '90 = 2 × 45 = 2 × 3 × 3 × 5 ; tous les facteurs sont premiers.'), q('45/60 sous forme irréductible vaut…', ['9/12', '3/4', '15/20'], 1, 'On divise les deux termes par 15.')]),
  lesson('puissances-scientifique', 'Puissances et racines carrées', 'Puissances et notation scientifique', 'Multiplier et diviser par 10, 100 et 1 000.', [
    ['Lire une puissance', 'aⁿ est le produit de n facteurs égaux à a pour n entier positif. Ainsi 4³ = 4 × 4 × 4 = 64, et non 4 × 3. Pour a non nul, a⁰ = 1.'],
    ['Utiliser les puissances de dix', '10⁻ⁿ = 1/10ⁿ. On a 10ᵐ × 10ⁿ = 10ᵐ⁺ⁿ et 10ᵐ ÷ 10ⁿ = 10ᵐ⁻ⁿ. Préfixes : nano 10⁻⁹, micro 10⁻⁶, milli 10⁻³, kilo 10³, méga 10⁶, giga 10⁹.'],
    ['Écrire et comparer en notation scientifique', 'Un nombre positif s’écrit a × 10ⁿ avec 1 ≤ a < 10 et n entier. Compare d’abord les exposants, puis les coefficients si les exposants sont égaux. Attention : (−3)² = 9 mais −3² = −9.'],
  ], ['Écrire 0,000056 en notation scientifique', 'Déplace mentalement la virgule pour obtenir 5,6, compris entre 1 et 10.', 'Il faut diviser 5,6 par 100 000 pour revenir au nombre initial.', '0,000056 = 5,6 × 10⁻⁵. Le signe négatif de l’exposant ne rend pas le nombre négatif.'], [
    ex('2⁵ = ?', 32, 'Écris cinq facteurs égaux à 2.', '2 × 2 × 2 × 2 × 2 = 32.'),
    ex('Un capteur mesure 7 millimètres. Quelle est cette longueur en mètres ?', .007, 'Milli signifie un millième.', '7 mm = 7 × 10⁻³ m = 0,007 m.'),
  ], [q('10³ × 10⁻⁵ = ?', ['10⁻²', '10⁻¹⁵', '10²'], 0, 'On additionne les exposants : 3 + (−5) = −2.'), q('Quelle écriture est scientifique ?', ['42 × 10³', '4,2 × 10⁴', '0,42 × 10⁵'], 1, 'Seul 4,2 est compris entre 1 inclus et 10 exclu.'), q('Quel nombre est le plus grand ?', ['8 × 10⁴', '9 × 10³', '2 × 10⁵'], 2, 'Ils valent respectivement 80 000, 9 000 et 200 000.')]),
  lesson('racines-carrees', 'Puissances et racines carrées', 'Carrés parfaits et racines carrées', 'Calculer le carré d’un nombre.', [
    ['Comprendre la racine carrée', 'Pour a ≥ 0, √a est l’unique nombre positif ou nul dont le carré vaut a. Ainsi √36 = 6. Dans les nombres réels, un nombre négatif n’a pas de racine carrée.'],
    ['Mémoriser les carrés utiles', 'De 1² à 12² : 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144. Ces repères permettent de contrôler un calcul.'],
    ['Encadrer et arrondir', 'Si 36 < a < 49 alors 6 < √a < 7. La calculatrice donne une approximation : conserve la forme √a pour une valeur exacte. En général √(a + b) ≠ √a + √b.'],
  ], ['Trouver le côté d’un carré d’aire 50 cm²', 'Si le côté mesure c cm, son aire vaut c² : c² = 50.', 'La longueur est positive : c = √50 cm.', '49 < 50 < 64, donc 7 < c < 8 ; à la calculatrice c ≈ 7,07 cm au centième.'], [
    ex('√121 = ?', 11, 'Quel nombre positif a pour carré 121 ?', '11 × 11 = 121, donc √121 = 11.'),
    ex('Un carré a une aire de 81 m². Quel est son périmètre en mètres ?', 36, 'Commence par trouver le côté.', 'Le côté mesure √81 = 9 m, puis P = 4 × 9 = 36 m.'),
  ], [q('√64 vaut…', ['−8', '8', '±8'], 1, 'La racine carrée est positive ou nulle : √64 = 8.'), q('Quel encadrement est juste ?', ['5 < √30 < 6', '15 < √30 < 16', '6 < √30 < 7'], 0, '25 < 30 < 36, donc 5 < √30 < 6.'), q('√9 + √16 = ?', ['√25', '25', '7'], 2, '3 + 4 = 7, alors que √25 = 5.')]),
  lesson('calcul-litteral', 'Calcul littéral et équations', 'Développer, réduire et factoriser', 'Connaître les priorités opératoires.', [
    ['Réduire une expression', 'Regroupe les termes de même nature : 4x + 2x = 6x, mais 4x + 2 ne se réduit pas. x × x = x² ; 2x + 3x² ne se réduit pas non plus.'],
    ['Développer un produit', 'La distributivité donne k(a + b) = ka + kb et k(a − b) = ka − kb. Multiplie chaque terme de la parenthèse, y compris son signe.'],
    ['Factoriser une somme', 'Mets le facteur commun en évidence : ka + kb = k(a + b). Pour prouver que deux programmes sont équivalents, compare leurs expressions réduites ; un seul exemple numérique ne suffit pas.'],
  ], ['Développer et réduire 5(2x − 3) + 4x', 'Distribue 5 : 5 × 2x − 5 × 3 + 4x = 10x − 15 + 4x.', 'Regroupe les termes en x : 10x + 4x = 14x.', 'L’expression réduite est 14x − 15. Pour x = 2, les deux écritures donnent 13.'], [
    ex('Calcule 3x² − 2 pour x = −2.', 10, 'Remplace x par (−2) en gardant les parenthèses.', '3 × (−2)² − 2 = 3 × 4 − 2 = 10.'),
    ex('Le périmètre d’un rectangle de côtés x et x + 3 vaut 4x + 6. Quelle est sa valeur pour x = 7 cm ?', 34, 'Remplace x par 7.', '2x + 2(x + 3) = 4x + 6 ; pour x = 7, cela donne 28 + 6 = 34 cm.'),
  ], [q('−2(x − 5) = ?', ['−2x − 10', '−2x + 10', '−2x + 5'], 1, '−2 × x + (−2) × (−5) = −2x + 10.'), q('6x + 18 se factorise en…', ['6(x + 3)', '6(x + 18)', '3(x + 6)'], 0, 'Les deux termes ont le facteur 6 en commun.'), q('3(x + 2) et 3x + 6 sont…', ['égaux seulement pour x = 0', 'jamais égaux', 'égaux pour tout x'], 2, 'La distributivité prouve cette égalité pour toute valeur de x.')]),
  lesson('equations', 'Calcul littéral et équations', 'Résoudre une équation et un problème', 'Réduire une expression littérale.', [
    ['Conserver une égalité', 'Une équation comporte une inconnue. Ajouter ou soustraire un même nombre aux deux membres conserve les solutions ; multiplier ou diviser les deux membres par un même nombre non nul aussi.'],
    ['Isoler l’inconnue', 'Regroupe les termes en x d’un côté et les nombres de l’autre, en effectuant la même opération des deux côtés. Termine en divisant par le coefficient non nul de x.'],
    ['Modéliser et vérifier', 'Définis l’inconnue et son unité, traduis l’énoncé, résous, puis remplace x dans l’équation initiale. Termine par une phrase répondant au problème et vérifie que la valeur est possible.'],
  ], ['Résoudre 5x + 3 = 2x + 18', 'Soustrais 2x aux deux membres : 3x + 3 = 18.', 'Soustrais 3 : 3x = 15 ; divise par 3 : x = 5.', 'Vérification : 5 × 5 + 3 = 28 et 2 × 5 + 18 = 28. La solution est 5.'], [
    ex('Résous 4x − 7 = 13. Quelle est la valeur de x ?', 5, 'Ajoute 7 puis divise par 4.', '4x = 20, donc x = 5. Vérification : 20 − 7 = 13.'),
    ex('Trois billets de même prix et 4 € de frais coûtent 31 €. Quel est le prix d’un billet en euros ?', 9, 'Si x est le prix d’un billet, écris 3x + 4 = 31.', '3x = 27, donc x = 9 €. Vérification : 3 × 9 + 4 = 31 €.'),
  ], [q('Résoudre 2x + 6 = 0 donne…', ['3', '−3', '−6'], 1, '2x = −6, donc x = −3.'), q('Pour conserver les solutions, on peut…', ['ajouter 4 seulement à gauche', 'diviser par zéro', 'soustraire 4 aux deux membres'], 2, 'On effectue la même opération valide dans les deux membres.'), q('4 est-il solution de 3x − 2 = 10 ?', ['Oui', 'Non', 'Impossible à tester'], 0, '3 × 4 − 2 = 12 − 2 = 10.')], 'equation'),
  lesson('proportionnalite-pourcentages', 'Proportionnalité et fonctions', 'Proportionnalité, pourcentages et échelles', 'Multiplier et diviser des décimaux.', [
    ['Reconnaître une proportionnalité', 'Deux grandeurs sont proportionnelles si on passe de l’une à l’autre par un même multiplicateur. Sur un graphique, les points sont alignés sur une droite passant par l’origine.'],
    ['Calculer une quatrième proportionnelle', 'Passe par l’unité ou utilise le coefficient. Si 3 objets identiques coûtent 7,50 €, un objet coûte 2,50 € et 8 objets coûtent 20 €.'],
    ['Appliquer un pourcentage ou une échelle', 't % d’une quantité Q vaut Q × t/100. Une baisse de t % donne Q × (1 − t/100). À l’échelle 1/n, longueur réelle = longueur sur le plan × n, avec les mêmes unités.'],
  ], ['Un sac à 65 € est soldé à −20 %', 'La réduction vaut 65 × 20/100 = 13 €.', 'Le nouveau prix vaut 65 − 13 = 52 €.', 'On peut aussi calculer 65 × 0,80 = 52 €. Une baisse de 20 % n’est pas une baisse de 20 €.'], [
    ex('5 cahiers identiques coûtent 12 €. Quel est le prix de 8 cahiers en euros ?', 19.2, 'Trouve le prix d’un cahier.', '12 ÷ 5 = 2,40 € ; 8 × 2,40 = 19,20 €.'),
    ex('À l’échelle 1/25 000, une route mesure 6 cm sur le plan. Quelle longueur réelle en km ?', 1.5, 'Calcule en cm, puis utilise 100 000 cm = 1 km.', '6 × 25 000 = 150 000 cm = 1 500 m = 1,5 km.'),
  ], [q('Augmenter 50 de 10 % donne…', ['55', '60', '45'], 0, '50 × 10/100 = 5 ; 50 + 5 = 55.'), q('Un tarif de 4 € fixes puis 2 €/km est-il proportionnel à la distance ?', ['Oui', 'Non', 'Toujours'], 1, 'À 0 km, le tarif vaut 4 € : il ne passe pas par l’origine.'), q('25 % de 64 vaut…', ['25', '32', '16'], 2, '25 % = 1/4, donc 64 ÷ 4 = 16.')]),
  lesson('grandeurs-graphiques', 'Proportionnalité et fonctions', 'Vitesses, débits et lecture de graphiques', 'Convertir des durées et lire des axes.', [
    ['Relier deux grandeurs', 'Une formule peut décrire une dépendance : pour un carré de côté c, A = c². Sur un graphique, pars de la valeur sur l’axe horizontal, rejoins la courbe, puis lis la valeur sur l’axe vertical.'],
    ['Calculer une vitesse ou un débit', 'Vitesse moyenne v = distance/durée ; distance = vitesse × durée. Débit = volume/durée. Les unités doivent être cohérentes : avec des km et des heures, la vitesse est en km/h.'],
    ['Convertir des unités composées', '1 h = 3 600 s et 1 km = 1 000 m, donc on divise les km/h par 3,6 pour obtenir des m/s. 1 m³ = 1 000 L ; 1 m³/s = 60 000 L/min. 1 h 30 = 1,5 h, pas 1,30 h.'],
  ], ['Un cycliste parcourt 27 km en 1 h 30', 'Convertis la durée : 1 h 30 = 1 + 30/60 = 1,5 h.', 'v = 27 ÷ 1,5 = 18 km/h.', '18 ÷ 3,6 = 5 m/s. Il s’agit d’une vitesse moyenne, pas nécessairement constante.'], [
    ex('Convertis 54 km/h en m/s.', 15, 'Divise par 3,6.', '54 ÷ 3,6 = 15 m/s.'),
    ex('Un robinet débite 0,002 m³/s. Quel est son débit en L/min ?', 120, 'Convertis d’abord les m³ en litres, puis les secondes en minutes.', '0,002 × 1 000 = 2 L/s ; 2 × 60 = 120 L/min.'),
  ], [q('À vitesse constante de 8 km/h, on parcourt en 15 min…', ['120 km', '2 km', '0,5 km'], 1, '15 min = 0,25 h et 8 × 0,25 = 2 km.'), q('Pour A = c², si c = 6 cm, A vaut…', ['12 cm²', '36 cm²', '6 cm²'], 1, 'L’aire est 6 × 6 = 36 cm² ; elle n’est pas proportionnelle au côté.'), q('Sur un graphique de température en fonction du temps, l’axe horizontal porte…', ['la température', 'l’aire', 'le temps'], 2, 'La température dépend du temps ; on lit le temps en abscisse.')], 'graph'),
  lesson('statistiques', 'Statistiques et probabilités', 'Moyenne, médiane et diagrammes', 'Ranger des nombres et calculer une somme.', [
    ['Calculer une moyenne', 'Additionne toutes les valeurs et divise par l’effectif total. Pour un tableau d’effectifs, multiplie chaque valeur par son effectif avant de sommer.'],
    ['Trouver une médiane', 'Range d’abord les valeurs. Avec un effectif impair, prends la valeur centrale ; avec un effectif pair, on choisit la moyenne des deux valeurs centrales. Au moins la moitié des données est de chaque côté, au sens large.'],
    ['Lire une distribution', 'Fréquence = effectif/total ; angle d’un secteur circulaire = fréquence × 360°. L’étendue est maximum − minimum. La moyenne peut être influencée par une valeur extrême ; distingue-la de la médiane.'],
  ], ['Étudier 3, 4, 4, 7, 12', 'La somme vaut 30, donc la moyenne vaut 30/5 = 6.', 'La série est rangée et comporte 5 valeurs : la médiane est la 3e, soit 4.', 'L’étendue vaut 12 − 3 = 9. Moyenne et médiane décrivent la série différemment.'], [
    ex('Quelle est la médiane de 9 ; 2 ; 8 ; 5 ?', 6.5, 'Range les quatre valeurs puis prends la moyenne des deux centrales.', '2 ; 5 ; 8 ; 9 : médiane = (5 + 8)/2 = 6,5.'),
    ex('Dans un club, 6 élèves sur 24 choisissent le tennis. Quel angle en degrés pour ce secteur du diagramme ?', 90, 'Multiplie la fréquence par 360.', '(6/24) × 360 = 90°.'),
  ], [q('Notes : 8 (effectif 2) et 14 (effectif 1). La moyenne vaut…', ['11', '10', '22'], 1, '(8 × 2 + 14)/3 = 30/3 = 10.'), q('Avant de chercher une médiane, il faut…', ['ranger les valeurs', 'additionner les extrêmes', 'multiplier les valeurs'], 0, 'La position centrale n’a de sens que dans une série ordonnée.'), q('Une fréquence de 0,3 correspond à…', ['3 %', '0,3 %', '30 %'], 2, '0,3 × 100 = 30 %.')]),
  lesson('probabilites', 'Statistiques et probabilités', 'Probabilités et événements contraires', 'Comprendre une fraction comme proportion.', [
    ['Décrire une expérience aléatoire', 'Une issue est un résultat possible ; un événement est un ensemble d’issues. Pour un dé à six faces, « obtenir un nombre pair » regroupe 2, 4 et 6.'],
    ['Calculer en équiprobabilité', 'Si les issues sont aussi probables les unes que les autres, P(événement) = nombre d’issues favorables/nombre total d’issues. Une probabilité appartient à [0 ; 1].'],
    ['Utiliser le contraire', 'L’événement contraire rassemble toutes les issues qui ne réalisent pas l’événement : P(contraire) = 1 − P(événement). Une fréquence observée varie ; elle n’est pas forcément égale à la probabilité théorique.'],
  ], ['Un sac contient 5 jetons verts et 3 jaunes, indiscernables au toucher', 'Les 8 jetons ont la même chance d’être tirés.', 'P(vert) = 5/8 = 0,625 = 62,5 %.', 'P(non vert) = 1 − 5/8 = 3/8, ici identique à P(jaune).'], [
    ex('Avec un dé équilibré à six faces, quelle est la probabilité d’obtenir un nombre supérieur à 4 ?', 1/3, 'Compte les issues 5 et 6.', '2 issues sur 6 : 2/6 = 1/3.'),
    ex('La probabilité de gagner est 0,28. Quelle est la probabilité de ne pas gagner ?', .72, 'Les deux probabilités s’additionnent pour donner 1.', '1 − 0,28 = 0,72, soit 72 %.'),
  ], [q('Une probabilité peut valoir…', ['−0,2', '1,4', '0,75'], 2, 'Elle est comprise entre 0 et 1.'), q('Le contraire de « obtenir 6 » est…', ['obtenir 1', 'obtenir un nombre différent de 6', 'obtenir un nombre pair'], 1, 'Le contraire comprend 1, 2, 3, 4 et 5.'), q('Après 10 piles consécutifs, pour une nouvelle pièce équilibrée lancée indépendamment, P(face) vaut…', ['1/2', '1', '0'], 0, 'Les lancers indépendants ne compensent pas les résultats précédents.')], 'probability'),
  lesson('pythagore', 'Pythagore, Thalès et cosinus', 'Pythagore et sa réciproque', 'Connaître les carrés et les racines carrées.', [
    ['Calculer dans un triangle rectangle', 'Dans ABC rectangle en A, le côté opposé à l’angle droit est l’hypoténuse BC. Le théorème de Pythagore donne BC² = AB² + AC².'],
    ['Chercher la bonne longueur', 'Pour l’hypoténuse, additionne les carrés des deux autres côtés. Pour un côté de l’angle droit, soustrais : AB² = BC² − AC². Prends ensuite la racine carrée positive.'],
    ['Prouver ou réfuter un angle droit', 'Pour tester un triangle, repère son plus grand côté. Si son carré égale la somme des deux autres carrés, la réciproque prouve que le triangle est rectangle. Sinon il ne l’est pas.'],
  ], ['ABC est rectangle en A ; AB = 9 cm et AC = 12 cm. Calculer BC.', 'L’hypoténuse est BC. D’après Pythagore, BC² = AB² + AC².', 'BC² = 81 + 144 = 225.', 'BC = √225 = 15 cm. Ce côté est bien plus long que 9 cm et 12 cm.'], [
    ex('Un triangle rectangle a pour hypoténuse 17 cm et pour autre côté 8 cm. Calcule le troisième côté en cm.', 15, 'Soustrais 8² de 17².', 'x² = 289 − 64 = 225, donc x = 15 cm.'),
    ex('Un rectangle mesure 5 m sur 12 m. Quelle est sa diagonale en mètres ?', 13, 'La diagonale est l’hypoténuse d’un triangle rectangle.', 'd² = 5² + 12² = 169, donc d = 13 m.'),
  ], [q('Un triangle de côtés 7, 24 et 25 est…', ['rectangle', 'équilatéral', 'non rectangle'], 0, '25² = 625 et 7² + 24² = 49 + 576 = 625 : réciproque de Pythagore.'), q('Pour des côtés 4, 6 et 7…', ['le triangle est rectangle', 'le triangle n’est pas rectangle', '7² = 4² + 6²'], 1, '49 ≠ 16 + 36 = 52.'), q('L’hypoténuse est…', ['un côté au choix', 'le plus petit côté', 'le côté opposé à l’angle droit'], 2, 'Dans un triangle rectangle, c’est aussi le plus long côté.')], 'pythagoras'),
  lesson('thales', 'Pythagore, Thalès et cosinus', 'Thalès : triangles emboîtés', 'Calculer une longueur par proportionnalité.', [
    ['Vérifier la configuration', 'Dans le triangle ABC, M est sur [AB], N sur [AC] et (MN) est parallèle à (BC). Les triangles AMN et ABC sont emboîtés. Les alignements et le parallélisme doivent être donnés ou prouvés.'],
    ['Écrire les rapports dans le même ordre', 'Le théorème donne AM/AB = AN/AC = MN/BC. Chaque numérateur est un côté du petit triangle, chaque dénominateur le côté correspondant du grand triangle.'],
    ['Démontrer un parallélisme', 'Réciproquement, si M appartient à [AB], N à [AC] et AM/AB = AN/AC (longueurs non nulles), alors (MN) est parallèle à (BC). Respecte l’ordre des points ; ne te fie pas au dessin.'],
  ], ['AM = 4, AB = 10, AC = 15 et MN ∥ BC. Calculer AN.', 'Les points A, M, B et A, N, C sont alignés dans cet ordre.', 'D’après Thalès : 4/10 = AN/15.', 'AN = 15 × 4/10 = 6. Le rapport de réduction est 0,4.'], [
    ex('M ∈ [AB], N ∈ [AC], MN ∥ BC ; AM = 3, AB = 9, BC = 18 cm. Quelle est MN en cm ?', 6, 'Utilise MN/18 = 3/9.', 'MN = 18 × 3/9 = 6 cm.'),
    ex('Avec AM/AB = AN/AC, AM = 6, AB = 8 et AN = 9 cm, quelle est AC en cm ?', 12, 'Écris 6/8 = 9/AC.', '6 × AC = 8 × 9 = 72 ; AC = 12 cm.'),
  ], [q('Quelle hypothèse est indispensable au théorème direct ?', ['Un angle droit', 'Le parallélisme des côtés concernés', 'Trois côtés égaux'], 1, 'Le parallélisme permet d’utiliser les rapports de Thalès.'), q('AM/AB = 2/5 et AC = 20 : AN vaut…', ['8', '50', '18'], 0, 'AN = 20 × 2/5 = 8.'), q('M ∈ [AB], N ∈ [AC] et AM/AB = AN/AC = 1/2. Alors…', ['MN ⟂ BC', 'A = M', 'MN ∥ BC'], 2, 'Les alignements et l’égalité des rapports permettent la réciproque.')]),
  lesson('cosinus-triangles', 'Pythagore, Thalès et cosinus', 'Cosinus et raisonnement sur les triangles', 'Repérer l’hypoténuse et les angles.', [
    ['Identifier les côtés d’un angle', 'Dans un triangle rectangle, le cosinus d’un angle aigu vaut longueur du côté adjacent/longueur de l’hypoténuse. Le côté adjacent touche l’angle et n’est pas l’hypoténuse.'],
    ['Calculer un côté ou un angle', 'Adjacent = hypoténuse × cos(angle) ; hypoténuse = adjacent/cos(angle). Pour trouver l’angle, utilise arccos ou cos⁻¹ sur la calculatrice réglée en degrés.'],
    ['Justifier l’égalité de triangles', 'Deux triangles sont superposables si leurs trois côtés correspondants sont égaux ; ou deux côtés et l’angle compris ; ou un côté et ses deux angles adjacents. Un dessin ressemblant ne constitue pas une preuve.'],
  ], ['ABC rectangle en A, BC = 10 cm et angle ABC = 60°. Calculer AB.', 'Par rapport à l’angle B, AB est adjacent et BC est l’hypoténuse.', 'cos(60°) = AB/10, donc AB = 10 × cos(60°).', 'cos(60°) = 0,5 : AB = 5 cm. Inversement arccos(5/10) = 60°.'], [
    ex('Un triangle rectangle a une hypoténuse de 14 cm et un angle de 60°. Quelle longueur du côté adjacent en cm ?', 7, 'Utilise cos(60°) = 0,5.', 'Adjacent = 14 × 0,5 = 7 cm.'),
    ex('Le côté adjacent mesure 6 cm et l’hypoténuse 10 cm. Quel est le cosinus de l’angle ?', .6, 'Divise adjacent par hypoténuse.', 'cos(angle) = 6/10 = 0,6. L’angle vaut environ 53,1°, mais on demandait son cosinus.'),
  ], [q('Le cosinus d’un angle aigu est…', ['supérieur à 1', 'entre 0 et 1', 'négatif'], 1, 'Le côté adjacent est positif et plus petit que l’hypoténuse.'), q('Deux triangles avec trois côtés correspondants égaux sont…', ['superposables', 'nécessairement rectangles', 'nécessairement équilatéraux'], 0, 'C’est le cas d’égalité par les trois côtés.'), q('Pour trouver l’angle dont le cosinus est 0,7, on utilise…', ['cos(0,7)', '0,7 × 90', 'arccos(0,7) en degrés'], 2, 'La fonction inverse du cosinus donne ici environ 45,6°.')]),
  lesson('translations-echelles', 'Espace et transformations', 'Translations, agrandissements et réductions', 'Lire les coordonnées dans un repère.', [
    ['Construire une translation', 'Une translation fait glisser tous les points dans une même direction, un même sens et sur une même distance. Pour construire une image, reporte le déplacement avec une parallèle et une longueur égale.'],
    ['Utiliser les conservations', 'Une translation conserve longueurs, angles, aires, alignement et parallélisme. Dans un repère, un déplacement de +3 horizontalement et −2 verticalement transforme (x ; y) en (x + 3 ; y − 2).'],
    ['Changer d’échelle', 'Dans un agrandissement ou une réduction de rapport k > 0, les longueurs sont multipliées par k, les aires par k² et les volumes par k³. Les angles ne changent pas.'],
  ], ['On double toutes les dimensions d’un pavé droit', 'Le rapport est k = 2 : chaque arête double.', 'Chaque aire de face est multipliée par 2² = 4.', 'Le volume est multiplié par 2³ = 8. Doubler les longueurs ne double pas le volume.'], [
    ex('A(−2 ; 5) est déplacé de +6 horizontalement et −3 verticalement. Quelle est l’abscisse de son image ?', 4, 'L’abscisse est la coordonnée horizontale.', 'A′ = (−2 + 6 ; 5 − 3) = (4 ; 2). Son abscisse est 4.'),
    ex('Une figure d’aire 45 cm² est réduite avec un rapport 1/3. Quelle est la nouvelle aire en cm² ?', 5, 'Multiplie l’aire par (1/3)².', '45 × 1/9 = 5 cm².'),
  ], [q('Une translation transforme un triangle en…', ['un triangle de même aire', 'un triangle deux fois plus grand', 'un cercle'], 0, 'Une translation conserve la forme et les dimensions.'), q('Avec k = 3, les volumes sont multipliés par…', ['3', '9', '27'], 2, 'Le coefficient sur les volumes est k³ = 27.'), q('Lors d’un agrandissement, les angles…', ['doublent', 'restent égaux', 'diminuent'], 1, 'Les rapports de longueurs changent, mais les angles sont conservés.')]),
  lesson('solides-volumes', 'Espace et transformations', 'Solides, repérage et volumes', 'Calculer une aire et convertir des longueurs.', [
    ['Se repérer et reconnaître les solides', 'Dans l’espace, on donne les coordonnées dans l’ordre (abscisse ; ordonnée ; altitude). Une pyramide a une base polygonale et des faces latérales triangulaires. Un cône de révolution a une base en disque et un sommet.'],
    ['Relier un solide à son patron', 'Le patron d’une pyramide à base carrée comporte un carré et quatre triangles qui se rejoignent au sommet. Celui d’un cône comporte un disque et un secteur de disque. En perspective, on trace les arêtes cachées en pointillés.'],
    ['Calculer un volume', 'Pyramide : V = aire de la base × hauteur/3. Cône : V = πr²h/3. La hauteur est perpendiculaire à la base ; ce n’est pas une arête oblique. Utilise une même unité de longueur et exprime le volume en unités cubes.'],
  ], ['Pyramide de base rectangulaire 6 cm × 4 cm et de hauteur 9 cm', 'L’aire de la base vaut 6 × 4 = 24 cm².', 'V = 24 × 9/3 = 72 cm³.', '72 cm³ = 72 mL. On a 1 L = 1 dm³ = 1 000 cm³.'], [
    ex('Un cône a un rayon de 3 cm et une hauteur de 8 cm. Son volume vaut kπ cm³. Quelle est la valeur de k ?', 24, 'Utilise r²h/3.', 'V = π × 3² × 8/3 = 24π cm³, soit environ 75,4 cm³.'),
    ex('Une pyramide a pour aire de base 35 m² et hauteur 6 m. Quel volume en m³ ?', 70, 'Multiplie l’aire de base par la hauteur, puis divise par 3.', 'V = 35 × 6/3 = 70 m³.'),
  ], [q('Dans P(2 ; 7 ; 5), l’altitude est…', ['2', '7', '5'], 2, 'L’altitude est la troisième coordonnée.'), q('Le patron d’un cône comporte…', ['un disque et un secteur de disque', 'deux carrés', 'six rectangles'], 0, 'Le disque forme la base et le secteur forme la surface latérale.'), q('2,5 L correspondent à…', ['250 cm³', '2 500 cm³', '25 cm³'], 1, '1 L = 1 000 cm³, donc 2,5 × 1 000 = 2 500 cm³.')]),
  lesson('algorithmique', 'Algorithmique', 'Variables, boucles et conditions', 'Suivre un programme de calcul.', [
    ['Suivre une variable', 'Une variable est une mémoire nommée. « Mettre score à 0 » remplace sa valeur ; « ajouter 2 à score » augmente sa valeur actuelle. Un événement, comme un clic sur le drapeau, déclenche le programme.'],
    ['Répéter des instructions', 'Une boucle « répéter n fois » exécute les instructions n fois. Pour tracer un carré : répéter 4 fois « avancer de 60 ; tourner de 90° ». Pour un triangle équilatéral, on tourne de 120°, angle extérieur.'],
    ['Tester et corriger', 'Une condition « si… alors… sinon… » choisit une branche. Prévois les cas inférieur, égal et supérieur au seuil. Un tableau de suivi note les valeurs à chaque étape pour repérer les erreurs.'],
  ], ['Mettre x à 1 ; répéter 4 fois « ajouter 3 à x » ; si x > 10 dire « gagné » sinon dire « encore »', 'Au départ x = 1.', 'Après chaque tour : 4, puis 7, puis 10, puis 13.', '13 > 10 : le message est « gagné ». Il y a quatre ajouts, pas trois.'], [
    ex('Mettre x à 2 ; répéter 3 fois « multiplier x par 2 ». Quelle valeur finale ?', 16, 'Écris la valeur après chaque tour.', 'Départ 2 ; après les tours : 4, 8, 16.'),
    ex('Un lutin trace un hexagone régulier. De combien de degrés doit-il tourner à chaque sommet ?', 60, 'Un tour complet fait 360° ; répartis-le entre 6 sommets.', '360/6 = 60°. C’est l’angle de rotation, pas l’angle intérieur de 120°.'),
  ], [q('Si x = 10, la condition x > 10 est…', ['vraie', 'fausse', 'aléatoire'], 1, 'Le signe > exclut l’égalité.'), q('Mettre x à 5 puis ajouter 2 à x donne…', ['2', '5', '7'], 2, 'Ajouter modifie la valeur actuelle : 5 + 2 = 7.'), q('Pour tracer un carré, on répète…', ['4 fois avancer puis tourner de 90°', '3 fois tourner de 90°', '4 fois tourner de 60°'], 0, 'Quatre côtés et quatre quarts de tour ferment le carré.')], 'algorithm'),
]

export const fourthChapters = [...new Set(fourthLessons.map(l => l.chapter))].map(title => ({ title, lessons: fourthLessons.filter(l => l.chapter === title) }))
