// Contenus originaux pour le programme de sixième applicable depuis 2025.
const q = (question, choices, correct, explanation) => ({question, choices, correct, explanation})
const e = (question, answer, hint, solution) => ({question, answer, hint, solution})
const l = (slug, chapter, title, prerequisite, rules, example, exercises, quiz, lab) => ({slug:'6e-'+slug,level:'6e',chapter,title,prerequisite,rules,objectives:rules.map(r=>r[0]),example,exercises,quiz,lab,duration:'10 à 15 min'})
export const sixthLessons = [
 l('decimaux','Nombres et calculs','Comprendre les nombres décimaux','Lire les nombres entiers.',[
 ['Quelle valeur a chaque chiffre ?','La position change la valeur. Dans 32,407 : 3 dizaines, 2 unités, 4 dixièmes, 0 centième et 7 millièmes. Un dixième vaut 0,1 ; un centième 0,01 ; un millième 0,001.'],
 ['Comment comparer deux décimaux ?','Compare les parties entières, puis les dixièmes, les centièmes… Tu peux compléter à droite par des zéros : 5,6 = 5,60 > 5,48. Avoir plus de chiffres ne signifie pas être plus grand.'],
 ['Comment arrondir ?','Au dixième, observe le chiffre des centièmes : de 0 à 4, garde le dixième ; de 5 à 9, augmente-le de 1. Ainsi 7,26 ≈ 7,3. Un arrondi est une approximation. Un milliard vaut 1 000 millions.']
 ],['Comparer 4,08 et 4,8','Les parties entières valent toutes les deux 4.','4,08 contient 0 dixième ; 4,8 contient 8 dixièmes.','Donc 4,08 < 4,8. On peut écrire 4,8 = 4,80.'],[
 e('Dans 25,638, quel est le chiffre des centièmes ?',3,'Regarde le deuxième rang après la virgule.','6 est le chiffre des dixièmes, 3 celui des centièmes et 8 celui des millièmes.'),
 e('Arrondis 12,76 au dixième.',12.8,'Observe le chiffre 6 des centièmes.','6 ≥ 5 : le chiffre des dixièmes passe de 7 à 8. L’arrondi est 12,8.')
 ],[q('Quelle égalité est vraie ?',['3,5 = 3,05','3,5 = 3,50','3,5 = 35'],1,'5 dixièmes = 50 centièmes.'),q('Quel est le plus petit nombre ?',['6,09','6,9','6,19'],0,'0 dixième est inférieur à 1 ou 9 dixièmes.'),q('Un milliard, c’est…',['1 000 000','100 000 000','1 000 000 000'],2,'Regroupe par classes : milliards, millions, milliers, unités.')],'place'),
 l('operations','Nombres et calculs','Calculer avec les décimaux','Connaître unités, dixièmes et centièmes.',[
 ['Comment poser une addition ?','Aligne les unités avec les unités et les virgules avec les virgules. Ajoute des zéros si nécessaire. Pour soustraire, utilise la même organisation.'],
 ['Comment multiplier des décimaux ?','1,2 × 0,3 = 12 dixièmes × 3 dixièmes = 36 centièmes = 0,36. Calcule avec les entiers, puis retrouve la bonne unité de numération.'],
 ['Comment vérifier un résultat ?','Estime d’abord : 9,8 × 3,1 est proche de 10 × 3 = 30. Multiplier par 0,1 revient à diviser par 10 ; par 0,01, à diviser par 100. Multiplier ne rend pas toujours plus grand.']
 ],['Une gourde coûte 8,75 € et une boîte 4,6 €. Quel total ?','Écris 4,6 = 4,60 pour aligner les centièmes.','8,75 + 4,60 = 13,35.','Le total est 13,35 €, proche de 9 + 5 = 14 €.'],[
 e('Calcule 7,4 − 2,85.',4.55,'Écris 7,40 − 2,85.','7,40 − 2,85 = 4,55.'),e('Une ficelle coûte 2,40 € le mètre. Combien coûtent 1,5 m, en euros ?',3.6,'1,5 m, c’est 1 m plus un demi-mètre.','2,40 + 1,20 = 3,60 €, ou 2,4 × 1,5 = 3,6.')
 ],[q('45 × 0,1 = ?',['450','4,5','0,45'],1,'Prendre un dixième, c’est diviser par 10.'),q('0,6 × 0,4 = ?',['0,24','2,4','24'],0,'6 dixièmes × 4 dixièmes = 24 centièmes.'),q('Pour 18,9 + 5,2, quel ordre de grandeur convient ?',['2','200','24'],2,'19 + 5 = 24.')]),
 l('division','Nombres et calculs','Partager et comprendre une division','Connaître les tables de multiplication.',[
 ['Qu’est-ce qu’une division euclidienne ?','Avec des entiers : dividende = diviseur × quotient + reste. Le diviseur est non nul et 0 ≤ reste < diviseur. Exemple : 38 = 5 × 7 + 3.'],
 ['Quand poursuivre après la virgule ?','Pour partager une longueur ou un prix, on peut poursuivre : 9 ÷ 4 = 2,25. Pour compter des cars ou des boîtes, interprète le reste selon la question.'],
 ['Comment reconnaître un multiple ?','Un multiple de 2 se termine par 0, 2, 4, 6 ou 8 ; de 5, par 0 ou 5 ; de 10, par 0. Un entier est divisible par 3 (ou 9) si la somme de ses chiffres est divisible par 3 (ou 9).']
 ],['On range 53 livres dans des boîtes de 8. Combien faut-il de boîtes ?','53 = 8 × 6 + 5 : six boîtes pleines et cinq livres restants.','Les cinq livres nécessitent une boîte supplémentaire.','Il faut 7 boîtes. Le quotient 6 ne suffit pas pour répondre.'],[
 e('Quel est le reste de la division euclidienne de 47 par 6 ?',5,'Cherche le plus grand multiple de 6 inférieur ou égal à 47.','47 = 6 × 7 + 5. Le reste 5 est inférieur à 6.'),e('Quatre amis partagent 18,60 € à parts égales. Quelle somme chacun paie-t-il en euros ?',4.65,'Divise 18,60 par 4.','18,60 ÷ 4 = 4,65 €. Vérification : 4 × 4,65 = 18,60.')
 ],[q('Quel reste est possible dans une division par 7 ?',['7','9','6'],2,'Le reste doit être inférieur à 7.'),q('Quel nombre est divisible par 3 ?',['124','123','125'],1,'1 + 2 + 3 = 6, divisible par 3.'),q('14 ÷ 4 = ?',['3,5','3,2','4'],0,'4 × 3,5 = 14.')]),
 l('fractions-sens','Fractions','Voir une fraction et comprendre un partage','Partager une unité en parts égales.',[
 ['Que disent les deux nombres d’une fraction ?','Dans 3/4, le dénominateur 4 indique quatre parts égales dans une unité ; le numérateur 3 indique trois de ces parts. Les parts doivent avoir la même taille.'],
 ['Une fraction peut-elle dépasser 1 ?','Oui : 7/4 = 1 + 3/4. Sur une demi-droite graduée en quarts, avance de sept quarts depuis zéro. Les fractions sont des nombres, pas seulement des morceaux de dessin.'],
 ['Quel lien avec la division ?','a/b est le quotient a ÷ b, pour b non nul. Partager 3 mètres entre 4 personnes donne 3/4 m à chacune. 1/3 est exact ; 0,33 n’en est qu’un arrondi au centième.']
 ],['Partager 5 mètres de ruban en 4 parts égales','Chaque part mesure 5 ÷ 4 = 5/4 m.','5/4 = 4/4 + 1/4 = 1 + 1/4.','Chaque part mesure 1,25 m. Vérification : 4 × 1,25 = 5.'],[
 e('Écris 3/4 sous forme décimale.',.75,'Calcule 3 ÷ 4.','3/4 = 75/100 = 0,75.'),e('Trois amis partagent 7 litres de jus à parts égales. Combien de litres chacun reçoit-il ? Donne une fraction exacte.',7/3,'Le partage se traduit par 7 ÷ 3.','Chaque ami reçoit 7/3 L. 2,33 L est un arrondi, pas la quantité exacte.')
 ],[q('Dans 5/8, le dénominateur est…',['5','8','13'],1,'Une unité est partagée en huit parts égales.'),q('7/4 est…',['inférieur à 1','égal à 1','supérieur à 1'],2,'7/4 = 1 + 3/4.'),q('Quel nombre multiplié par 5 donne 3 ?',['3/5','5/3','15'],0,'5 × (3/5) = 3.')],'fraction'),
 l('fractions-calcul','Fractions','Comparer et additionner des fractions','Comprendre le numérateur et le dénominateur.',[
 ['Comment obtenir une fraction égale ?','Multiplie ou divise les deux termes par un même nombre non nul : 2/3 = 4/6. On change l’écriture, pas la quantité.'],
 ['Comment comparer deux fractions ?','Si les dénominateurs sont égaux et positifs, compare les numérateurs. Sinon, cherche des parts de même taille : 1/2 = 3/6, donc 1/2 < 4/6.'],
 ['Comment additionner ou soustraire ?','Avec un même dénominateur, additionne ou soustrais les numérateurs et garde le dénominateur. Pour 1/2 + 1/4, écris 2/4 + 1/4 = 3/4. On n’additionne pas les dénominateurs.']
 ],['Calculer 2/3 + 1/6','Transforme les tiers en sixièmes : 2/3 = 4/6.','Ajoute les parts de même taille : 4/6 + 1/6 = 5/6.','Le résultat exact est 5/6, inférieur à 1.'],[
 e('Calcule 3/8 + 2/8. Écris une fraction.',5/8,'Les parts sont déjà de même taille.','3/8 + 2/8 = 5/8.'),e('Tu bois 1/4 L le matin et 1/2 L à midi. Combien de litres au total ?',.75,'Écris le demi-litre en quarts.','1/4 + 2/4 = 3/4 L, soit 0,75 L.')
 ],[q('Quelle fraction est égale à 3/5 ?',['6/5','3/10','6/10'],2,'On multiplie les deux termes par 2.'),q('5/7 − 2/7 = ?',['3/7','3/0','7/7'],0,'Cinq septièmes moins deux septièmes font trois septièmes.'),q('1/3 comparé à 1/2 donne…',['1/3 > 1/2','1/3 < 1/2','égalité'],1,'Dans une même unité, un tiers est plus petit qu’un demi.')]),
 l('fractions-quantites','Fractions','Prendre une fraction ou un pourcentage','Diviser un entier par un petit nombre.',[
 ['Comment prendre une fraction d’une quantité ?','Pour prendre 3/5 de 20, cherche un cinquième : 20 ÷ 5 = 4. Prends-en trois : 4 × 3 = 12.'],
 ['Que signifie un pourcentage ?','t % signifie t sur 100. Donc 50 % = 1/2 ; 25 % = 1/4 ; 75 % = 3/4 ; 10 % = 1/10.'],
 ['Comment multiplier une fraction par un entier ?','4 × (2/3) = 8/3. Multiplie le numérateur par l’entier et garde le dénominateur. On peut le comprendre comme quatre fois deux tiers.']
 ],['Dans un club de 28 élèves, 25 % viennent à vélo. Combien d’élèves ?','25 % = 25/100 = 1/4.','Un quart de 28 vaut 28 ÷ 4 = 7.','7 élèves viennent à vélo.'],[
 e('Combien vaut 3/4 de 32 ?',24,'Commence par un quart de 32.','32 ÷ 4 = 8 ; 8 × 3 = 24.'),e('Une classe de 30 élèves compte 40 % de demi-pensionnaires. Combien sont-ils ?',12,'10 % de 30 vaut 3 ; prends quatre fois cette quantité.','40 % de 30 = 4 × 3 = 12 élèves.')
 ],[q('50 % de 18 vaut…',['9','50','36'],0,'La moitié de 18 vaut 9.'),q('3 × (2/5) = ?',['6/15','6/5','5/5'],1,'Trois fois deux cinquièmes font six cinquièmes.'),q('0,75 correspond à…',['7,5 %','25 %','75 %'],2,'0,75 = 75/100 = 75 %.')]),
 l('longueurs','Grandeurs et mesures','Mesurer des longueurs et des périmètres','Additionner et multiplier.',[
 ['Comment convertir une longueur ?','1 km = 1 000 m ; 1 m = 100 cm ; 1 cm = 10 mm. Convertis les longueurs dans une même unité avant de calculer.'],
 ['Qu’est-ce qu’un périmètre ?','C’est la longueur du contour. Rectangle : P = 2 × (L + l). Carré : P = 4 × côté. Le résultat s’exprime en cm, m… et non en cm².'],
 ['Comment mesurer le tour d’un cercle ?','Le diamètre vaut deux rayons. La longueur du cercle vaut π × diamètre, soit 2 × π × rayon. Pour une approximation, on peut utiliser π ≈ 3,14.']
 ],['Un rectangle mesure 2 m sur 80 cm. Quel périmètre ?','Convertis 80 cm en 0,8 m.','P = 2 × (2 + 0,8) = 5,6.','Le périmètre est 5,6 m, soit 560 cm.'],[
 e('Convertis 3,25 m en centimètres.',325,'Un mètre contient 100 centimètres.','3,25 × 100 = 325 cm.'),e('Un cercle a un diamètre de 10 cm. Calcule son périmètre en cm en utilisant π = 3,14.',31.4,'Multiplie le diamètre par 3,14.','P ≈ 3,14 × 10 = 31,4 cm.')
 ],[q('Le périmètre d’un carré de côté 6 cm vaut…',['36 cm','24 cm','12 cm'],1,'Quatre côtés de 6 cm : 4 × 6 = 24.'),q('Un cercle de rayon 7 cm a un diamètre de…',['14 cm','7 cm','3,5 cm'],0,'Le diamètre vaut deux rayons.'),q('Pour mesurer un contour, on utilise…',['des cm²','des cm³','des cm'],2,'Le périmètre est une longueur.')]),
 l('aires','Grandeurs et mesures','Distinguer aire et périmètre','Compter les cases d’un quadrillage.',[
 ['Qu’est-ce qu’une aire ?','L’aire mesure la surface à l’intérieur d’une figure. Un carré de 1 cm de côté a une aire de 1 cm². Compte les carrés unités, puis regroupe-les.'],
 ['Comment calculer une aire ?','Rectangle : longueur × largeur. Carré : côté × côté. Triangle : base × hauteur correspondante ÷ 2. La hauteur est perpendiculaire à la base.'],
 ['Comment convertir une aire ?','1 m² = 10 000 cm² : un carré de 1 m contient 100 rangées de 100 carrés de 1 cm. Attention : même périmètre ne signifie pas forcément même aire.']
 ],['Trouver l’aire d’un triangle de base 8 cm et de hauteur 5 cm','Le rectangle de 8 cm sur 5 cm a une aire de 40 cm².','Le triangle occupe la moitié de ce rectangle.','Aire = 8 × 5 ÷ 2 = 20 cm².'],[
 e('Quelle est l’aire d’un rectangle de 7 cm sur 4 cm, en cm² ?',28,'Compte 4 rangées de 7 carrés.','7 × 4 = 28 cm².'),e('Un triangle a une base de 9 cm et une hauteur correspondante de 6 cm. Quelle aire en cm² ?',27,'Prends la moitié du produit de la base par la hauteur.','9 × 6 ÷ 2 = 27 cm².')
 ],[q('Un rectangle de 5 cm sur 3 cm a une aire de…',['16 cm²','8 cm²','15 cm²'],2,'5 × 3 = 15 ; 16 cm serait son périmètre.'),q('1 m² contient…',['100 cm²','10 000 cm²','1 000 cm²'],1,'100 × 100 = 10 000 carrés de 1 cm².'),q('Pour un triangle, la hauteur est…',['perpendiculaire à la base','toujours son plus long côté','toujours égale à la base'],0,'On utilise une base et la hauteur perpendiculaire correspondante.')],'area'),
 l('volumes','Grandeurs et mesures','Compter des cubes et comparer des volumes','Compter par rangées.',[
 ['Qu’est-ce qu’un centimètre cube ?','Un cube d’arête 1 cm occupe un volume de 1 cm³. Le volume mesure la place occupée dans l’espace, pas un contour ni une surface.'],
 ['Comment compter un assemblage ?','Compte les cubes d’une couche, puis les couches. N’oublie pas les cubes cachés. Si les couches sont identiques, multiplie leur effectif par leur nombre.'],
 ['Comment comparer deux volumes ?','Utilise le même cube unité. Un assemblage de 18 cubes unités a un plus grand volume qu’un assemblage de 15, même si ce dernier est plus haut.']
 ],['Une construction a 3 couches de 8 cubes d’arête 1 cm','Chaque couche a un volume de 8 cm³.','Trois couches contiennent 3 × 8 = 24 cubes.','Le volume est 24 cm³.'],[
 e('Combien de cm³ occupent 4 couches de 6 cubes de 1 cm³ ?',24,'Multiplie le nombre de couches par les cubes d’une couche.','4 × 6 = 24 cubes, donc 24 cm³.'),e('On enlève 5 cubes de 1 cm³ à un assemblage de 32 cubes. Quel volume reste-t-il en cm³ ?',27,'On retire 5 unités de volume.','32 − 5 = 27 cm³.')
 ],[q('1 cm³ correspond au volume…',['d’un carré de côté 1 cm','d’un cube d’arête 1 cm','d’un segment de 1 cm'],1,'Un volume s’étend dans trois directions.'),q('Pour compter les cubes, il faut inclure…',['seulement les cubes visibles','seulement ceux du dessus','les cubes cachés aussi'],2,'Ils occupent eux aussi une place.'),q('Trois couches de 10 cubes donnent…',['30 cubes','13 cubes','100 cubes'],0,'10 + 10 + 10 = 30.')]),
 l('durees','Grandeurs et mesures','Lire un horaire et calculer une durée','Lire les heures et les minutes.',[
 ['Quelles conversions retenir ?','1 jour = 24 heures ; 1 heure = 60 minutes ; 1 minute = 60 secondes. Les durées ne se convertissent pas de dix en dix.'],
 ['Comment calculer entre deux horaires ?','Avance jusqu’à l’heure suivante, puis jusqu’à l’arrivée. Un horaire repère un instant ; une durée mesure le temps écoulé.'],
 ['Comment additionner des durées ?','Additionne les minutes, puis échange 60 minutes contre 1 heure si nécessaire. 1 h 30 min = 1,5 h, et non 1,30 h.']
 ],['Un atelier commence à 14 h 45 et finit à 16 h 10','De 14 h 45 à 15 h : 15 minutes.','De 15 h à 16 h 10 : 1 h 10 min.','Durée totale : 1 h 25 min, soit 85 minutes.'],[
 e('Combien de minutes y a-t-il dans 2 h 15 min ?',135,'Deux heures font deux fois 60 minutes.','2 × 60 + 15 = 135 minutes.'),e('Un trajet débute à 9 h 50 et finit à 10 h 35. Combien de minutes dure-t-il ?',45,'Passe par 10 heures.','10 minutes jusqu’à 10 h, puis 35 : 45 minutes.')
 ],[q('90 minutes, c’est…',['1 h 30','1 h 90','9 h'],0,'90 = 60 + 30.'),q('3 minutes font…',['30 secondes','180 secondes','300 secondes'],1,'3 × 60 = 180 secondes.'),q('23 h 40 à 0 h 10 le lendemain représente…',['70 minutes','10 minutes','30 minutes'],2,'20 minutes jusqu’à minuit, puis 10.')]),
 l('droites-cercle','Espace et géométrie','Tracer des droites et des cercles','Utiliser une règle.',[
 ['Droite, segment ou demi-droite ?','[AB] est le segment limité par A et B ; (AB) est la droite, illimitée dans les deux sens ; [AB) est la demi-droite d’origine A passant par B. AB désigne la longueur du segment.'],
 ['Parallèles ou perpendiculaires ?','Deux droites perpendiculaires se coupent à angle droit : vérifie à l’équerre. Deux droites parallèles distinctes ne se rencontrent pas. Deux droites perpendiculaires à une même droite sont parallèles.'],
 ['Comment définir un cercle ?','Un cercle de centre O et de rayon r rassemble les points situés exactement à la distance r de O. Au compas, garde la pointe en O et un écartement constant. Le disque contient aussi l’intérieur.']
 ],['Tracer un cercle de centre O et de rayon 3 cm','Marque O et mesure 3 cm d’écartement au compas avec la règle.','Place la pointe sèche en O et fais tourner le compas sans changer l’écartement.','Tout point du cercle est à 3 cm de O ; son diamètre mesure 6 cm.'],[
 e('Un cercle a un diamètre de 18 cm. Quel est son rayon en cm ?',9,'Le rayon vaut la moitié du diamètre.','18 ÷ 2 = 9 cm.'),e('M est sur le cercle de centre O et de rayon 4,5 cm. Quelle est OM en cm ?',4.5,'Tous les points du cercle sont à la même distance du centre.','OM est un rayon : OM = 4,5 cm.')
 ],[q('La notation [AB] désigne…',['une droite','un segment','une longueur'],1,'Les crochets indiquent les extrémités du segment.'),q('Deux droites perpendiculaires forment…',['un angle droit','un angle de 30°','un cercle'],0,'L’angle droit mesure 90°.'),q('Un point à 2 cm du centre d’un cercle de rayon 5 cm est…',['sur le cercle','à l’extérieur du disque','à l’intérieur du disque'],2,'2 < 5 : il est à l’intérieur, mais pas sur le cercle.')]),
 l('angles','Espace et géométrie','Mesurer des angles et tracer une bissectrice','Reconnaître un angle droit.',[
 ['Comment classer un angle ?','Un angle aigu est entre 0° et 90° ; un angle droit vaut 90° ; un angle obtus est entre 90° et 180° ; un angle plat vaut 180°. Un tour complet vaut 360°.'],
 ['Comment utiliser un rapporteur ?','Place son centre sur le sommet. Aligne le zéro d’une graduation sur un côté. Lis cette graduation jusqu’à l’autre côté. Vérifie si la valeur correspond à un angle aigu ou obtus.'],
 ['Qu’est-ce qu’une bissectrice ?','La bissectrice partage un angle en deux angles égaux. Pour un angle de 70°, elle forme deux angles de 35°. Elle est aussi un axe de symétrie de l’angle.']
 ],['Tracer la bissectrice d’un angle de 110°','Calcule la moitié : 110 ÷ 2 = 55°.','Centre le rapporteur au sommet et marque 55° d’un côté, à l’intérieur de l’angle.','Trace la droite passant par le sommet et le repère. Les deux angles mesurent 55°.'],[
 e('Combien mesure un quart de tour, en degrés ?',90,'Un tour complet vaut 360°.','360 ÷ 4 = 90°.'),e('Une bissectrice partage un angle de 86°. Quelle est la mesure de chaque moitié, en degrés ?',43,'Divise la mesure par deux.','86 ÷ 2 = 43°.')
 ],[q('Un angle de 125° est…',['aigu','droit','obtus'],2,'125 est compris entre 90 et 180.'),q('Le centre du rapporteur se place…',['sur le sommet','au milieu d’un côté','n’importe où'],0,'Le sommet est le point commun aux côtés.'),q('Un angle plat mesure…',['90°','180°','360°'],1,'Il correspond à un demi-tour.')],'angle'),
 l('triangles','Espace et géométrie','Construire et reconnaître des triangles','Tracer un segment et utiliser un compas.',[
 ['Quels triangles reconnaître ?','Un triangle isocèle a au moins deux côtés égaux ; un équilatéral a trois côtés égaux ; un rectangle a un angle droit. Les codages indiquent les égalités et l’angle droit.'],
 ['Que vaut la somme des angles ?','Les trois angles d’un triangle totalisent 180°. Dans un équilatéral, chaque angle vaut 60°. Dans un isocèle, les deux angles à la base sont égaux.'],
 ['Comment construire avec trois longueurs ?','Trace un côté. Au compas, trace un arc depuis chaque extrémité, aux rayons correspondant aux autres côtés. Une intersection donne le troisième sommet. Le plus grand côté doit être plus petit que la somme des deux autres pour un triangle non aplati.']
 ],['Deux angles d’un triangle mesurent 45° et 65°. Trouver le troisième.','La somme connue vaut 45 + 65 = 110°.','La somme des trois angles vaut 180°.','Le troisième angle mesure 180 − 110 = 70°.'],[
 e('Un triangle rectangle a un angle aigu de 32°. Combien mesure l’autre angle aigu, en degrés ?',58,'Enlève 90° et 32° à 180°.','180 − 90 − 32 = 58°.'),e('Un triangle isocèle a un angle au sommet de 40°. Combien mesure chacun des angles à la base ?',70,'Les deux angles égaux se partagent 180 − 40.','(180 − 40) ÷ 2 = 70°.')
 ],[q('Peut-on construire un triangle de côtés 2, 3 et 8 cm ?',['Oui','Non','Toujours'],1,'2 + 3 = 5 < 8 : les petits côtés ne peuvent pas se rejoindre.'),q('Un triangle équilatéral possède…',['trois angles de 60°','un angle de 90°','trois angles de 90°'],0,'180 ÷ 3 = 60°.'),q('Pour reporter une longueur, on utilise…',['le rapporteur','l’équerre seule','le compas'],2,'Le compas conserve un écartement.')]),
 l('symetrie','Espace et géométrie','Comprendre la symétrie et la médiatrice','Tracer des perpendiculaires.',[
 ['Que fait une symétrie axiale ?','Imagine un pliage le long d’une droite : les figures doivent se superposer. Un point et son image sont à même distance de l’axe, de part et d’autre. Un point de l’axe reste en place.'],
 ['Comment construire l’image d’un point ?','Trace la perpendiculaire à l’axe passant par le point. Reporte de l’autre côté la même distance à l’axe. La symétrie conserve longueurs, angles et aires.'],
 ['Qu’est-ce qu’une médiatrice ?','La médiatrice d’un segment est la droite perpendiculaire au segment passant par son milieu. Ses points sont à égale distance des extrémités. La bissectrice, elle, concerne un angle.']
 ],['A est à 3 carreaux à gauche d’un axe vertical. Placer A′.','Trace mentalement l’horizontale passant par A, perpendiculaire à l’axe.','Compte 3 carreaux à droite de l’axe sur cette ligne.','A′ est à la même hauteur que A. L’axe passe au milieu de [AA′].'],[
 e('A est à 4 cm de l’axe. Quelle est la longueur AA′ en cm ?',8,'Le segment comporte deux distances égales.','AA′ = 4 + 4 = 8 cm.'),e('M est sur la médiatrice de [AB] et MA = 6 cm. Quelle est MB en cm ?',6,'Un point de la médiatrice est à égale distance de A et B.','MA = MB = 6 cm.')
 ],[q('L’image d’un point situé sur l’axe est…',['le même point','toujours plus haut','impossible à tracer'],0,'Un point de l’axe ne bouge pas.'),q('La médiatrice passe…',['par une extrémité seulement','par le milieu, perpendiculairement au segment','n’importe où'],1,'Il faut milieu et perpendicularité.'),q('Une symétrie conserve…',['seulement les couleurs','seulement le nombre de sommets','les longueurs et les angles'],2,'La figure et son image sont superposables.')],'symmetry'),
 l('solides','Espace et géométrie','Reconnaître les solides et leurs vues','Distinguer figure plane et objet dans l’espace.',[
 ['Face, arête ou sommet ?','Une face est une surface plane d’un polyèdre ; une arête est un segment où se rejoignent deux faces ; un sommet est un point où se rejoignent des arêtes. Un cube a 6 faces, 12 arêtes et 8 sommets.'],
 ['Quels solides reconnaître ?','Un pavé droit a six faces rectangulaires ; un cube est un pavé droit dont toutes les arêtes sont égales. Un cylindre a deux bases en disque. Une pyramide a une base polygonale et des faces latérales triangulaires.'],
 ['Comment passer du volume au dessin ?','Une vue de dessus montre l’empreinte ; une vue de face montre les hauteurs visibles. Un patron se replie pour former le solide. Pour compter des cubes, pense aux cubes masqués.']
 ],['Quatre colonnes de cubes ont pour hauteurs 1, 2, 3 et 2','Chaque colonne occupe une case vue de dessus.','Le nombre total de cubes est 1 + 2 + 3 + 2 = 8.','La vue de dessus comporte 4 cases, mais la construction contient 8 cubes.'],[
 e('Combien d’arêtes a un cube ?',12,'Compte 4 en haut, 4 en bas et 4 verticales.','4 + 4 + 4 = 12 arêtes.'),e('Trois colonnes contiennent 2, 4 et 3 cubes. Combien de cubes au total ?',9,'Additionne les hauteurs des colonnes.','2 + 4 + 3 = 9 cubes.')
 ],[q('Toutes les faces d’un cube sont…',['des triangles','des carrés','des disques'],1,'Les six faces sont des carrés superposables.'),q('Une vue de dessus permet toujours de compter tous les cubes cachés.',['Vrai','Seulement si les couleurs diffèrent','Faux'],2,'Plusieurs hauteurs peuvent avoir la même empreinte.'),q('Un patron sert à…',['reconstituer un solide par pliage','mesurer un angle','calculer un quotient'],0,'Les faces doivent se rejoindre sans chevauchement.')]),
 l('donnees','Données et probabilités','Lire un tableau et un diagramme','Additionner des entiers.',[
 ['Comment lire un tableau ?','Lis le titre, les en-têtes et les unités. Dans un tableau à double entrée, croise la bonne ligne et la bonne colonne. Un effectif est le nombre d’éléments d’une catégorie.'],
 ['Comment lire un diagramme ?','Sur des barres, lis l’échelle : un intervalle peut représenter 1, 5 ou 10 élèves. Pour une courbe, relie la valeur horizontale à la valeur verticale correspondante.'],
 ['Comment mener une enquête ?','Pose une question précise, recueille une réponse par personne, compte les catégories puis présente les résultats. La somme des effectifs doit correspondre au nombre de réponses.']
 ],['Livres empruntés : lundi 12, mardi 18, mercredi 15','Mardi correspond à 18 livres.','Le total est 12 + 18 + 15 = 45 livres.','Mardi dépasse lundi de 18 − 12 = 6 livres.'],[
 e('Un club compte 8 élèves en dessin, 12 en théâtre et 5 en musique, sans double inscription. Quel effectif total ?',25,'Additionne les catégories.','8 + 12 + 5 = 25 élèves.'),e('Une barre atteint la 7e graduation au-dessus de zéro. Chaque intervalle représente 5 élèves. Quel effectif ?',35,'Chaque intervalle vaut 5, pas 1.','7 × 5 = 35 élèves.')
 ],[q('Avant de lire une barre, je regarde…',['sa couleur seulement','l’échelle et les unités','le nombre de lettres du titre'],1,'La hauteur dépend de la graduation.'),q('Un effectif est…',['un nombre d’éléments','une longueur','un angle'],0,'Il compte des individus ou des objets.'),q('7 réponses A et 13 réponses B donnent…',['13 réponses','7 réponses','20 réponses'],2,'7 + 13 = 20.')]),
 l('hasard','Données et probabilités','Comprendre les chances et les probabilités','Lire une fraction et un pourcentage.',[
 ['Qu’est-ce qu’une issue ?','C’est un résultat possible d’une expérience aléatoire. Un dé équilibré peut donner 1, 2, 3, 4, 5 ou 6. Avant le lancer, on ne sait pas quelle face sortira.'],
 ['Comment calculer une probabilité ?','Si les issues ont la même chance, divise le nombre d’issues favorables par le total. Pour obtenir un nombre pair sur un dé : 3/6 = 1/2 = 50 %.'],
 ['Est-ce une promesse de résultat ?','Non : 50 % de chances ne veut pas dire exactement 5 réussites sur 10 essais. La fréquence est la proportion observée. Un événement impossible a une probabilité 0 ; un événement certain a une probabilité 1.']
 ],['Un sac contient 2 jetons rouges et 3 bleus, identiques au toucher','Les 5 jetons ont la même chance d’être tirés.','Deux conviennent pour obtenir rouge : probabilité = 2/5.','2/5 = 0,4 = 40 %. Cela ne prédit pas la couleur du prochain tirage.'],[
 e('Quelle est la probabilité d’obtenir 6 avec un dé équilibré à six faces ? Donne une fraction.',1/6,'Une seule face convient parmi six.','La probabilité vaut 1/6.'),e('Sur 20 essais, on obtient 5 fois rouge. Quelle fréquence observe-t-on ? Écris un décimal.',.25,'Divise les succès par le nombre d’essais.','5/20 = 1/4 = 0,25, soit 25 %.')
 ],[q('Obtenir 8 avec un dé numéroté de 1 à 6 est…',['certain','impossible','une chance sur deux'],1,'Aucune face ne porte 8.'),q('1/4 correspond à…',['25 %','4 %','75 %'],0,'1/4 = 25/100.'),q('Deux couleurs sont forcément équiprobables dans un sac.',['Oui','Seulement le lundi','Non'],2,'Il faut connaître le nombre de jetons de chaque couleur.')]),
 l('proportionnalite','Proportionnalité','Résoudre un problème de proportionnalité','Multiplier et diviser.',[
 ['Comment reconnaître la proportionnalité ?','Si une quantité est multipliée par 2, 3… l’autre l’est aussi. Des objets identiques au même prix unitaire : deux fois plus d’objets coûtent deux fois plus cher.'],
 ['Comment passer par l’unité ?','Si 4 cahiers coûtent 10 €, un cahier coûte 10 ÷ 4 = 2,50 €. Six coûtent 6 × 2,50 = 15 €. On raisonne avec le sens du problème, sans produit en croix.'],
 ['Comment lire une échelle simple ?','Si 1 cm sur le plan représente 2 m en réalité, 3 cm représentent 6 m. Les longueurs correspondantes se multiplient dans la même proportion. Vérifie les unités.']
 ],['Pour 4 personnes, il faut 300 g de riz. Combien pour 6 personnes ?','Pour 2 personnes, il faut la moitié : 150 g.','6 personnes, c’est 4 plus 2.','300 + 150 = 450 g. Autre méthode : 75 g par personne, puis 75 × 6.'],[
 e('Trois carnets identiques coûtent 7,50 €. Combien coûtent cinq carnets, en euros ?',12.5,'Trouve le prix d’un carnet.','7,50 ÷ 3 = 2,50 ; 5 × 2,50 = 12,50 €.'),e('Sur un plan, 1 cm représente 4 m. Une allée mesure 7 cm sur le plan. Quelle longueur réelle en mètres ?',28,'Chaque centimètre représente 4 mètres.','7 × 4 = 28 m.')
 ],[q('Si le prix est proportionnel, trois fois plus d’objets coûtent…',['3 € de plus','trois fois plus','le même prix'],1,'Les deux grandeurs sont multipliées par 3.'),q('La taille d’un enfant est-elle proportionnelle à son âge ?',['Non','Oui','Toujours'],0,'Doubler l’âge ne double pas systématiquement la taille.'),q('2 kg coûtent 6 €. Au même prix par kg, 5 kg coûtent…',['9 €','30 €','15 €'],2,'1 kg coûte 3 €, puis 5 × 3 = 15 €.')] ,'ratio'),
 l('algebre','Nombres et calculs','Trouver un nombre caché et utiliser une formule','Comprendre les quatre opérations.',[
 ['Comment compléter une égalité ?','Le signe = signifie que les deux côtés ont la même valeur. Pour □ + 8 = 21, calcule 21 − 8 = 13 puis vérifie : 13 + 8 = 21.'],
 ['À quoi sert une lettre ?','Elle représente un nombre. P = 4 × c donne le périmètre d’un carré de côté c. Si c = 5, alors P = 4 × 5 = 20. Remplace la lettre par la valeur donnée.'],
 ['Comment expliquer un motif qui grandit ?','Repère ce qui reste fixe et ce qui s’ajoute. Pour n groupes de 3 points et 1 point isolé, le total est 3 × n + 1. La règle doit décrire toutes les étapes.']
 ],['Une frise comporte n groupes de 4 perles et 2 perles de fermeture. Combien pour 5 groupes ?','La formule est 4 × n + 2.','Remplace n par 5 : 4 × 5 + 2.','20 + 2 = 22 perles. Les deux perles fixes ne sont ajoutées qu’une fois.'],[
 e('Complète : □ + 17 = 42.',25,'Cherche ce qu’il faut ajouter à 17.','42 − 17 = 25 ; 25 + 17 = 42.'),e('Une frise a 3 × n + 2 points. Combien pour n = 6 ?',20,'Calcule les groupes, puis ajoute les points fixes.','3 × 6 + 2 = 18 + 2 = 20 points.')
 ],[q('Quel nombre complète 5 × □ = 35 ?',['30','7','40'],1,'35 ÷ 5 = 7.'),q('Si c = 8, alors 4 × c vaut…',['32','48','12'],0,'4 × 8 = 32.'),q('Dans 2 × n + 5, n désigne…',['toujours 2','toujours 5','un nombre dont la valeur peut varier'],2,'La lettre permet d’écrire une règle générale.')]),
 l('instructions','Pensée informatique','Suivre des instructions et des répétitions','Se repérer sur un quadrillage.',[
 ['Qu’est-ce qu’un algorithme ?','C’est une suite d’instructions précises pour accomplir une tâche. L’ordre compte : avancer puis tourner ne donne pas toujours le même résultat que tourner puis avancer.'],
 ['Pourquoi utiliser une répétition ?','Pour éviter de réécrire les mêmes instructions. Répéter 3 fois « avancer de 2 cases » fait avancer de 6 cases si la direction ne change pas.'],
 ['Comment repérer une erreur ?','Exécute une instruction à la fois et note la position à chaque étape. Compare avec la destination souhaitée. Corrige l’instruction, puis teste de nouveau.']
 ],['Depuis la case 0, répéter 4 fois « avancer de 2 cases »','Après un tour : case 2 ; après deux : case 4.','Après trois tours : case 6 ; après quatre : case 8.','La position finale est 8. Quatre tours représentent quatre déplacements.'],[
 e('Depuis 0, on répète 5 fois « ajouter 3 ». Quel nombre obtient-on ?',15,'Écris 3 + 3 + 3 + 3 + 3.','5 × 3 = 15.'),e('Un motif comporte 4 carrés. On le répète 6 fois sans chevauchement. Combien de carrés ?',24,'Compte six groupes identiques.','6 × 4 = 24 carrés.')
 ],[q('Pour vérifier un programme, je peux…',['deviner sans lire','suivre les étapes une à une','ignorer l’ordre'],1,'Une trace étape par étape aide à trouver l’erreur.'),q('Répéter 3 fois « avancer de 2 » équivaut à…',['avancer de 6','avancer de 5','avancer de 2'],0,'2 + 2 + 2 = 6.'),q('Une instruction utile doit être…',['vague','très longue','précise'],2,'On doit pouvoir l’exécuter sans deviner.')],'steps'),
]
export const sixthChapters = [...new Set(sixthLessons.map(l=>l.chapter))].map(title=>({title,lessons:sixthLessons.filter(l=>l.chapter===title)}))
