import { sixthLessons } from './lessons/sixieme.js'
import { fourthLessons } from './lessons/quatrieme.js'
const extra = {
 '5e': [
 ['Calculs','Dans quel ordre effectuer 7 + 3 × 4 ?','La multiplication d’abord : 3 × 4 = 12, puis 7 + 12 = 19. Avec des parenthèses, on commence par leur contenu.'],
 ['Calculs','Que signifie multiplier par 0,1 ?','Prendre un dixième, donc diviser par 10. Exemple : 27 × 0,1 = 2,7.'],
 ['Relatifs','Que sont deux nombres opposés ?','Ils sont à la même distance de zéro, de signes contraires. Exemple : −6 et +6. Leur somme vaut 0.'],
 ['Relatifs','Comment comparer deux nombres négatifs ?','Le plus proche de zéro est le plus grand. Exemple : −3 > −8. Sur une droite graduée, le plus grand est le plus à droite.'],
 ['Relatifs','Comment additionner deux relatifs de même signe ?','Additionne les distances à zéro et garde le signe commun. Exemple : −4 + (−7) = −11.'],
 ['Relatifs','Comment additionner deux relatifs de signes différents ?','Soustrais les distances à zéro et garde le signe du nombre le plus éloigné de zéro. Exemple : −9 + 5 = −4.'],
 ['Relatifs','Comment soustraire un nombre relatif ?','Ajoute son opposé : 3 − (−5) = 3 + 5 = 8.'],
 ['Fractions','Comment fabriquer une fraction égale à 3/4 ?','Multiplie les deux termes par le même nombre non nul : 3/4 = 6/8 = 9/12.'],
 ['Fractions','Comment calculer 2/3 + 1/6 ?','Écris 2/3 = 4/6, puis 4/6 + 1/6 = 5/6. On garde le dénominateur commun.'],
 ['Fractions','Comment comparer 3/4 et 5/8 ?','3/4 = 6/8, donc 3/4 > 5/8. Les huitièmes ont tous la même taille.'],
 ['Calcul littéral','Que signifie 5x ?','5 × x. Si x = 3, alors 5x = 15. Cela ne signifie pas 5 + x.'],
 ['Calcul littéral','Comment développer 4(x + 2) ?','Distribue 4 aux deux termes : 4x + 8.'],
 ['Calcul littéral','Comment tester une égalité pour x = 2 ?','Remplace chaque x par 2 et calcule séparément les deux membres. Ils doivent avoir la même valeur. Un seul test ne prouve pas une égalité pour tout x.'],
 ['Proportionnalité','Comment passer par l’unité ?','Si 3 objets coûtent 12 €, un objet coûte 4 €. Cinq objets identiques coûtent donc 20 €.'],
 ['Proportionnalité','Comment calculer 15 % de 80 ?','80 × 15/100 = 12. On peut aussi additionner 10 % (8) et 5 % (4).'],
 ['Géométrie','Combien vaut la somme des angles d’un triangle ?','180°. Si deux angles valent 40° et 60°, le troisième vaut 80°.'],
 ['Géométrie','Que fait une symétrie centrale de centre O ?','Un demi-tour autour de O. Si A a pour image A′, alors O est le milieu de [AA′]. Les longueurs et les angles sont conservés.'],
 ['Géométrie','Quelle propriété caractérise les diagonales d’un parallélogramme ?','Elles se coupent en leur milieu. Un parallélogramme est un quadrilatère dont les côtés opposés sont parallèles.'],
 ['Géométrie','Comment calculer l’aire d’un triangle ?','Base × hauteur correspondante ÷ 2. La hauteur est perpendiculaire à la base.'],
 ['Mesures','Quel est le volume d’un prisme droit ?','Aire de la base × hauteur, avec des unités cohérentes. Exemple : 12 cm² × 5 cm = 60 cm³.'],
 ['Mesures','Quel est le volume d’un cylindre ?','π × rayon² × hauteur. Le rayon est la moitié du diamètre.'],
 ['Données','Comment calculer une moyenne ?','Additionne les valeurs puis divise par leur nombre. Pour 6, 9 et 12 : 27 ÷ 3 = 9.'],
 ['Données','Comment calculer une probabilité si les issues sont équiprobables ?','Nombre d’issues favorables ÷ nombre total d’issues. Sur un dé équilibré, P(nombre pair) = 3/6 = 1/2.'],
 ['Algorithmique','Que signifie « répéter 4 fois » ?','Exécuter exactement quatre fois les instructions de la boucle. Note le résultat après chaque tour pour vérifier.'],
 ],
 '3e': [
 ['Nombres','Qu’est-ce qu’un nombre premier ?','Un entier supérieur à 1 ayant exactement deux diviseurs positifs : 1 et lui-même. 2 est premier ; 1 ne l’est pas.'],
 ['Nombres','Comment rendre 42/70 irréductible ?','Divise les deux termes par 14 : 42/70 = 3/5. Il ne reste aucun diviseur commun supérieur à 1.'],
 ['Nombres','Comment multiplier deux puissances de même base ?','aᵐ × aⁿ = aᵐ⁺ⁿ. Exemple : 10³ × 10⁻⁵ = 10⁻². Pour les exposants négatifs, a doit être non nul.'],
 ['Nombres','Quelle est la forme d’une notation scientifique positive ?','a × 10ⁿ avec 1 ≤ a < 10 et n entier. Exemple : 0,0042 = 4,2 × 10⁻³.'],
 ['Algèbre','Comment développer (a + b)² ?','a² + 2ab + b². Exemple : (x + 3)² = x² + 6x + 9.'],
 ['Algèbre','Comment développer (a − b)² ?','a² − 2ab + b². Attention au signe du double produit.'],
 ['Algèbre','Comment factoriser a² − b² ?','(a − b)(a + b). Exemple : x² − 25 = (x − 5)(x + 5).'],
 ['Algèbre','Comment résoudre un produit nul ?','Un produit est nul si au moins un facteur est nul. (x − 2)(x + 5) = 0 donne x = 2 ou x = −5.'],
 ['Fonctions','Que signifie f(3) = 7 ?','7 est l’image de 3 par f ; 3 est un antécédent de 7. Une valeur peut avoir plusieurs antécédents.'],
 ['Fonctions','Quelle forme a une fonction linéaire ?','f(x) = ax. Elle traduit une proportionnalité ; sa droite passe par l’origine.'],
 ['Fonctions','Quelle forme a une fonction affine ?','f(x) = ax + b. Sa représentation est une droite ; b est l’ordonnée à l’origine.'],
 ['Fonctions','Quel coefficient applique une hausse de 12 % ?','1 + 12/100 = 1,12. Pour une baisse de 12 %, on multiplie par 0,88.'],
 ['Géométrie','Quand utiliser Pythagore ?','Dans un triangle rectangle : hypoténuse² = somme des carrés des deux autres côtés. Pour prouver un angle droit, on utilise la réciproque.'],
 ['Géométrie','Quelles vérifications avant Thalès ?','Vérifie les alignements et le parallélisme. Écris les rapports des côtés correspondants dans le même ordre.'],
 ['Géométrie','Quelles sont les trois formules trigonométriques ?','Dans un triangle rectangle, pour un angle aigu : cos = adjacent/hypoténuse ; sin = opposé/hypoténuse ; tan = opposé/adjacent.'],
 ['Géométrie','Comment retrouver un angle à partir de son cosinus ?','Utilise arccos (ou cos⁻¹) sur la calculatrice réglée en degrés. Par exemple arccos(0,5) = 60°.'],
 ['Géométrie','Qu’est-ce qu’une homothétie de centre O et de rapport k non nul ?','O, A et son image A′ sont alignés et OA′ = |k| × OA. Si k > 0, A et A′ sont du même côté de O ; si k < 0, ils sont de côtés opposés.'],
 ['Géométrie','Que deviennent aires et volumes si les longueurs sont multipliées par k > 0 ?','Les aires sont multipliées par k² et les volumes par k³. Pour k = 2 : aires × 4, volumes × 8.'],
 ['Mesures','Quel est le volume d’une boule de rayon r ?','V = 4πr³/3. L’aire de la sphère qui la délimite vaut 4πr². Ne confonds pas surface et volume.'],
 ['Données','Comment trouver la médiane d’une petite série ?','Range les valeurs. Effectif impair : valeur centrale ; effectif pair : on choisit la moyenne des deux valeurs centrales.'],
 ['Données','Comment calculer une moyenne pondérée ?','Somme des valeurs multipliées par leurs effectifs, divisée par l’effectif total.'],
 ['Probabilités','Comment trouver la probabilité de l’événement contraire ?','P(contraire de A) = 1 − P(A). Exemple : si P(A) = 0,3, alors P(non A) = 0,7.'],
 ['Algorithmique','À quoi sert une condition « si… alors… sinon… » ?','Elle choisit une branche selon qu’un test est vrai ou faux. Vérifie aussi le cas d’égalité au seuil.'],
 ['Méthode brevet','Comment présenter une démonstration ?','Énonce les données utiles, cite la propriété avec ses conditions, applique-la, puis conclus avec la bonne unité si nécessaire.'],
 ]
}
export const memoryCards = {
 '6e': [
  ...sixthLessons.flatMap(lesson=>lesson.rules.map(([question,answer],i)=>({id:`${lesson.slug}-${i}`,topic:lesson.chapter,question,answer,href:`/niveau/6e/lecon/${lesson.slug}`}))),
  ...Array.from({length:8},(_,i)=>i+2).flatMap(a=>Array.from({length:10-a},(_,i)=>i+a).map(b=>({id:`6e-table-${a}-${b}`,topic:'Tables de multiplication',question:`Combien font ${a} × ${b} ?`,answer:`${a} × ${b} = ${a*b}. Donc ${b} × ${a} = ${a*b}, ${a*b} ÷ ${a} = ${b} et ${a*b} ÷ ${b} = ${a}.`})))
 ],
 '4e': fourthLessons.flatMap(lesson=>lesson.rules.map(([title,answer],i)=>({id:`4e-${lesson.slug}-${i}`,topic:lesson.chapter,question:`Explique la règle : ${title.toLowerCase()}.`,answer,href:`/niveau/4e/lecon/${lesson.slug}`}))),
 '5e': extra['5e'].map(([topic,question,answer],i)=>({id:`5e-base-${i}`,topic,question,answer})),
 '3e': extra['3e'].map(([topic,question,answer],i)=>({id:`3e-base-${i}`,topic,question,answer})),
}
